#
#     This file is part of CasADi.
# 
#     CasADi -- A symbolic framework for dynamic optimization.
#     Copyright (C) 2010 by Joel Andersson, Moritz Diehl, K.U.Leuven. All rights reserved.
# 
#     CasADi is free software; you can redistribute it and/or
#     modify it under the terms of the GNU Lesser General Public
#     License as published by the Free Software Foundation; either
#     version 3 of the License, or (at your option) any later version.
# 
#     CasADi is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     Lesser General Public License for more details.
# 
#     You should have received a copy of the GNU Lesser General Public
#     License along with CasADi; if not, write to the Free Software
#     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
# 
# 
src = 'src'
out = 'pdf'

import sys
args=sys.argv[1:]

try:
	from pyreport import *
except:
	raise Exception("Unable to compile.\n\nPlease install pyreport with 'sudo easy_install pyreport' to compile the tutorials")

try:
	import casadi
except:
	raise Exception("Couldn't load casadi's python module. Make sure you have compiled them with 'make python' and make sure you have set your PYTHONPATH to link to casadi's build_dir/swig_interface and build_dir/lib")


import os

def pyrep(indir,name,outdir):
	try:
		os.makedirs(outdir)
	except:
		pass
	cmd= "pyreport -d -l %s" % (os.path.join(indir,name))
	print cmd
	(base,ext)=os.path.splitext(name)
	pdfname = base + ".pdf"
	os.system(cmd)
	if not(os.path.exists(os.path.join(indir,pdfname))):
		raise Exception("pyreport failed to create a pdf output. Please check for errors generated by pyreports.")
	try:
		os.rename(os.path.join(indir,pdfname), os.path.join(outdir,pdfname))
	except OSError:
		if os.path.exists(os.path.join(outdir,pdfname)):
			os.remove(os.path.join(outdir,pdfname))
			os.rename(os.path.join(indir,pdfname), os.path.join(outdir,pdfname))
		print "Couldn't move to output directory."
		pass 
		
for root, dirs, files in os.walk(src):
	for name in files:
		if '.svn' in dirs:
			dirs.remove('.svn') # don't visit svn folders
		if len(args)>0 and all(map(lambda a: name.find(a)==-1,args)):
			continue
		if name.endswith('.py'):
			relroot=os.path.relpath(root,src)
			pyrep(root,name,os.path.join(out,relroot))
			
			
			
