/*
 *    This file is part of CasADi.
 *
 *    CasADi -- A symbolic framework for dynamic optimization.
 *    Copyright (C) 2010 by Joel Andersson, Moritz Diehl, K.U.Leuven. All rights reserved.
 *
 *    CasADi is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    CasADi is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with CasADi; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


      #include "qpoases_internal.hpp"
      #include <string>

      const std::string casadi::QPOasesInternal::meta_doc=
      "\n"
"\n"
">List of available options\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"|       Id        |      Type       |     Default     |   Description   |\n"
"+=================+=================+=================+=================+\n"
"| CPUtime         | OT_REAL         | None            | The maximum     |\n"
"|                 |                 |                 | allowed CPU     |\n"
"|                 |                 |                 | time in seconds |\n"
"|                 |                 |                 | for the whole   |\n"
"|                 |                 |                 | initialisation  |\n"
"|                 |                 |                 | (and the        |\n"
"|                 |                 |                 | actually        |\n"
"|                 |                 |                 | required one on |\n"
"|                 |                 |                 | output).        |\n"
"|                 |                 |                 | Disabled if     |\n"
"|                 |                 |                 | unset.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| ad_mode         | OT_STRING       | \"automatic\"     | How to          |\n"
"|                 |                 |                 | calculate the   |\n"
"|                 |                 |                 | Jacobians.      |\n"
"|                 |                 |                 | (forward: only  |\n"
"|                 |                 |                 | forward         |\n"
"|                 |                 |                 | mode|reverse:   |\n"
"|                 |                 |                 | only adjoint    |\n"
"|                 |                 |                 | mode|automatic: |\n"
"|                 |                 |                 | a heuristic     |\n"
"|                 |                 |                 | decides which   |\n"
"|                 |                 |                 | is more         |\n"
"|                 |                 |                 | appropriate)    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| boundRelaxation | OT_REAL         | 10000           | Initial         |\n"
"|                 |                 |                 | relaxation of   |\n"
"|                 |                 |                 | bounds to start |\n"
"|                 |                 |                 | homotopy and    |\n"
"|                 |                 |                 | initial value   |\n"
"|                 |                 |                 | for far bounds. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| boundTolerance  | OT_REAL         | 0.000           | If upper and    |\n"
"|                 |                 |                 | lower bounds    |\n"
"|                 |                 |                 | differ less     |\n"
"|                 |                 |                 | than this       |\n"
"|                 |                 |                 | tolerance, they |\n"
"|                 |                 |                 | are regarded    |\n"
"|                 |                 |                 | equal, i.e. as  |\n"
"|                 |                 |                 | equality        |\n"
"|                 |                 |                 | constraint.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| derivative_gene | OT_DERIVATIVEGE | GenericType()   | Function that   |\n"
"| rator           | NERATOR         |                 | returns a       |\n"
"|                 |                 |                 | derivative      |\n"
"|                 |                 |                 | function given  |\n"
"|                 |                 |                 | a number of     |\n"
"|                 |                 |                 | forward and     |\n"
"|                 |                 |                 | reverse         |\n"
"|                 |                 |                 | directional     |\n"
"|                 |                 |                 | derivative,     |\n"
"|                 |                 |                 | overrides       |\n"
"|                 |                 |                 | internal        |\n"
"|                 |                 |                 | routines. Check |\n"
"|                 |                 |                 | documentation   |\n"
"|                 |                 |                 | of DerivativeGe |\n"
"|                 |                 |                 | nerator.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableCholeskyR | OT_INTEGER      | 0               | Specifies the   |\n"
"| efactorisation  |                 |                 | frequency of a  |\n"
"|                 |                 |                 | full re-        |\n"
"|                 |                 |                 | factorisation   |\n"
"|                 |                 |                 | of projected    |\n"
"|                 |                 |                 | Hessian matrix: |\n"
"|                 |                 |                 | 0: turns them   |\n"
"|                 |                 |                 | off, 1: uses    |\n"
"|                 |                 |                 | them at each    |\n"
"|                 |                 |                 | iteration etc.  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableDriftCorr | OT_INTEGER      | 1               | Specifies the   |\n"
"| ection          |                 |                 | frequency of    |\n"
"|                 |                 |                 | drift           |\n"
"|                 |                 |                 | corrections: 0: |\n"
"|                 |                 |                 | turns them off. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableEqualitie | OT_BOOLEAN      | False           | Specifies       |\n"
"| s               |                 |                 | whether         |\n"
"|                 |                 |                 | equalities      |\n"
"|                 |                 |                 | should be       |\n"
"|                 |                 |                 | treated as      |\n"
"|                 |                 |                 | always active   |\n"
"|                 |                 |                 | (True) or not   |\n"
"|                 |                 |                 | (False)         |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableFarBounds | OT_BOOLEAN      | True            | Enables the use |\n"
"|                 |                 |                 | of far bounds.  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableFlippingB | OT_BOOLEAN      | True            | Enables the use |\n"
"| ounds           |                 |                 | of flipping     |\n"
"|                 |                 |                 | bounds.         |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableFullLITes | OT_BOOLEAN      | False           | Enables         |\n"
"| ts              |                 |                 | condition-      |\n"
"|                 |                 |                 | hardened (but   |\n"
"|                 |                 |                 | more expensive) |\n"
"|                 |                 |                 | LI test.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableNZCTests  | OT_BOOLEAN      | True            | Enables nonzero |\n"
"|                 |                 |                 | curvature       |\n"
"|                 |                 |                 | tests.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableRamping   | OT_BOOLEAN      | True            | Enables         |\n"
"|                 |                 |                 | ramping.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| enableRegularis | OT_BOOLEAN      | False           | Enables         |\n"
"| ation           |                 |                 | automatic       |\n"
"|                 |                 |                 | Hessian         |\n"
"|                 |                 |                 | regularisation. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsDen          | OT_REAL         | 0.000           | Denominator     |\n"
"|                 |                 |                 | tolerance for   |\n"
"|                 |                 |                 | ratio tests.    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsFlipping     | OT_REAL         | 0.000           | Tolerance of    |\n"
"|                 |                 |                 | squared         |\n"
"|                 |                 |                 | Cholesky        |\n"
"|                 |                 |                 | diagonal factor |\n"
"|                 |                 |                 | which triggers  |\n"
"|                 |                 |                 | flipping bound. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsIterRef      | OT_REAL         | 0.000           | Early           |\n"
"|                 |                 |                 | termination     |\n"
"|                 |                 |                 | tolerance for   |\n"
"|                 |                 |                 | iterative       |\n"
"|                 |                 |                 | refinement.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsLITests      | OT_REAL         | 0.000           | Tolerance for   |\n"
"|                 |                 |                 | linear          |\n"
"|                 |                 |                 | independence    |\n"
"|                 |                 |                 | tests.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsNZCTests     | OT_REAL         | 0.000           | Tolerance for   |\n"
"|                 |                 |                 | nonzero         |\n"
"|                 |                 |                 | curvature       |\n"
"|                 |                 |                 | tests.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsNum          | OT_REAL         | -0.000          | Numerator       |\n"
"|                 |                 |                 | tolerance for   |\n"
"|                 |                 |                 | ratio tests.    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| epsRegularisati | OT_REAL         | 0.000           | Scaling factor  |\n"
"| on              |                 |                 | of identity     |\n"
"|                 |                 |                 | matrix used for |\n"
"|                 |                 |                 | Hessian         |\n"
"|                 |                 |                 | regularisation. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| finalRamping    | OT_REAL         | 1               | Final value for |\n"
"|                 |                 |                 | ramping         |\n"
"|                 |                 |                 | strategy.       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gather_stats    | OT_BOOLEAN      | false           | Flag to         |\n"
"|                 |                 |                 | indicate        |\n"
"|                 |                 |                 | whether         |\n"
"|                 |                 |                 | statistics must |\n"
"|                 |                 |                 | be gathered     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| growFarBounds   | OT_REAL         | 1000            | Factor to grow  |\n"
"|                 |                 |                 | far bounds.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| initialFarBound | OT_REAL         | 1000000         | Initial size    |\n"
"| s               |                 |                 | for far bounds. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| initialRamping  | OT_REAL         | 0.500           | Start value for |\n"
"|                 |                 |                 | ramping         |\n"
"|                 |                 |                 | strategy.       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| initialStatusBo | OT_STRING       | lower           | Initial status  |\n"
"| unds            |                 |                 | of bounds at    |\n"
"|                 |                 |                 | first           |\n"
"|                 |                 |                 | iteration.      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| inputs_check    | OT_BOOLEAN      | true            | Throw           |\n"
"|                 |                 |                 | exceptions when |\n"
"|                 |                 |                 | the numerical   |\n"
"|                 |                 |                 | values of the   |\n"
"|                 |                 |                 | inputs don't    |\n"
"|                 |                 |                 | make sense      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| maxDualJump     | OT_REAL         | 100000000       | Maximum allowed |\n"
"|                 |                 |                 | jump in dual    |\n"
"|                 |                 |                 | variables in    |\n"
"|                 |                 |                 | linear          |\n"
"|                 |                 |                 | independence    |\n"
"|                 |                 |                 | tests.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| maxPrimalJump   | OT_REAL         | 100000000       | Maximum allowed |\n"
"|                 |                 |                 | jump in primal  |\n"
"|                 |                 |                 | variables in    |\n"
"|                 |                 |                 | nonzero         |\n"
"|                 |                 |                 | curvature       |\n"
"|                 |                 |                 | tests.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| monitor         | OT_STRINGVECTOR | GenericType()   | Monitors to be  |\n"
"|                 |                 |                 | activated (inpu |\n"
"|                 |                 |                 | ts|outputs)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| nWSR            | OT_INTEGER      | None            | The maximum     |\n"
"|                 |                 |                 | number of       |\n"
"|                 |                 |                 | working set     |\n"
"|                 |                 |                 | recalculations  |\n"
"|                 |                 |                 | to be performed |\n"
"|                 |                 |                 | during the      |\n"
"|                 |                 |                 | initial         |\n"
"|                 |                 |                 | homotopy.       |\n"
"|                 |                 |                 | Default is 5(nx |\n"
"|                 |                 |                 | + nc)           |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| name            | OT_STRING       | \"unnamed_shared | name of the     |\n"
"|                 |                 | _object\"        | object          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| numRefinementSt | OT_INTEGER      | 1               | Maximum number  |\n"
"| eps             |                 |                 | of iterative    |\n"
"|                 |                 |                 | refinement      |\n"
"|                 |                 |                 | steps.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| numRegularisati | OT_INTEGER      | 0               | Maximum number  |\n"
"| onSteps         |                 |                 | of successive   |\n"
"|                 |                 |                 | regularisation  |\n"
"|                 |                 |                 | steps.          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| printLevel      | OT_STRING       | medium          | Defines the     |\n"
"|                 |                 |                 | amount of text  |\n"
"|                 |                 |                 | output during   |\n"
"|                 |                 |                 | QP solution,    |\n"
"|                 |                 |                 | see Section 5.7 |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| regularity_chec | OT_BOOLEAN      | true            | Throw           |\n"
"| k               |                 |                 | exceptions when |\n"
"|                 |                 |                 | NaN or Inf      |\n"
"|                 |                 |                 | appears during  |\n"
"|                 |                 |                 | evaluation      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| terminationTole | OT_REAL         | 0.000           | Relative        |\n"
"| rance           |                 |                 | termination     |\n"
"|                 |                 |                 | tolerance to    |\n"
"|                 |                 |                 | stop homotopy.  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| user_data       | OT_VOIDPTR      | GenericType()   | A user-defined  |\n"
"|                 |                 |                 | field that can  |\n"
"|                 |                 |                 | be used to      |\n"
"|                 |                 |                 | identify the    |\n"
"|                 |                 |                 | function or     |\n"
"|                 |                 |                 | pass additional |\n"
"|                 |                 |                 | information     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| verbose         | OT_BOOLEAN      | false           | Verbose         |\n"
"|                 |                 |                 | evaluation  for |\n"
"|                 |                 |                 | debugging       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"\n"
"\n"
"\n"
"\n"
;
