# TRY TO FIND THE INCLUDE DIRECTORY
FIND_PATH(OOQP_INCLUDE_DIR 
QpGenData.h
HINTS /usr/local/include/ooqp/
)

SET(OOQP_LIBRARIES ${BLAS_LIBRARIES} ${HSL_LIBRARIES})

IF (OOQP_INCLUDE_DIR)
  SET(OOQP_FOUND_INCLUDE TRUE)
  SET(OOQP_INCLUDE_DIRS 
  ${OOQP_INCLUDE_DIR})
  MESSAGE(STATUS "Found OOQP include dirs: ${OOQP_INCLUDE_DIRS}")
ELSE (OOQP_INCLUDE_DIR)
  MESSAGE(STATUS "Could not find OOQP include dir")
ENDIF (OOQP_INCLUDE_DIR)

# TRY TO FIND THE LIBRARIES
SET(OOQP_LIBS_LIST
  ooqpgensparse ooqpsparse ooqpgondzio ooqpbase
)

SET(OOQP_FOUND_LIBS TRUE)
FOREACH(LIB ${OOQP_LIBS_LIST})
  FIND_LIBRARY(OOQP_LIB_${LIB}
    NAMES ${LIB}
    HINTS /usr/local/libs/)
  IF(OOQP_LIB_${LIB})
    SET(OOQP_LIBRARIES ${OOQP_LIBRARIES} ${OOQP_LIB_${LIB}})
  ELSE(OOQP_LIB_${LIB})
    SET(OOQP_FOUND_LIBS FALSE)
  ENDIF(OOQP_LIB_${LIB})
ENDFOREACH(LIB)

# print OOQP_LIBRARIES
IF(OOQP_FOUND_LIBS)
  MESSAGE(STATUS "Found OOQP libraries: ${OOQP_LIBRARIES}")  
ELSEIF(OOQP_FOUND_INCLUDE AND OOQP_FOUND_LIBS)
  MESSAGE(STATUS "Cound not find OOQP libraries")  
ENDIF(OOQP_FOUND_LIBS)

# SUCCESS IF BOTH THE LIBRARIES AND THE INCLUDE DIRECTORIES WERE FOUND
IF(OOQP_FOUND_INCLUDE AND OOQP_FOUND_LIBS)
  SET(OOQP_FOUND TRUE)
  MESSAGE(STATUS "Found OOQP")  
ELSEIF(OOQP_FOUND_INCLUDE AND OOQP_FOUND_LIBS)
  MESSAGE(STATUS "Cound not find OOQP")  
ENDIF(OOQP_FOUND_INCLUDE AND OOQP_FOUND_LIBS)


