# TRY TO FIND THE MA27 LIBRARY

FIND_LIBRARY(MA27_LIB
    NAMES MA27
    HINTS /usr/local/lib/)

IF(MA27_LIB)
  MESSAGE(STATUS "Found MA27: ${MA27_LIB}")
  SET(MA27_LIBRARIES ${MA27_LIB})
  SET(MA27_FOUND TRUE)
ELSE(MA27_LIB)
  SET(MA27_FOUND FALSE)
  MESSAGE(STATUS "Could not find MA27")
ENDIF(MA27_LIB)
