# TRY TO FIND THE INCLUDE DIRECTORY
FIND_PROGRAM(OCTAVE_EXECUTABLE octave
PATHS "C:/Octave/*/bin"
)

IF(OCTAVE_EXECUTABLE)
  SET(OCTAVE_FOUND TRUE)
ELSE(OCTAVE_EXECUTABLE)
  SET(OCTAVE_FOUND FALSE)
ENDIF(OCTAVE_EXECUTABLE)

