# TRY TO FIND THE INCLUDE DIRECTORY
FIND_PROGRAM(OCTAVE_EXECUTABLE octave
PATHS "C:/Octave/*/bin"
)

FILE(GLOB OCTAVE_INCLUDE_PATHS 
  "/usr/include/octave-*/"
  "/opt/local/include/octave-*/"
)

FIND_PATH(OCTAVE_INCLUDE_DIR octave/oct.h
HINTS ${OCTAVE_INCLUDE_PATH} ${OCTAVE_INCLUDE_PATHS}
)

FILE(GLOB OCTAVE_LINK_PATHS 
  "/usr/lib/octave/*/"
  "/opt/local/lib/octave/*/"
)

FIND_LIBRARY(OCTAVE_LIBRARY octave                             
HINTS ${OCTAVE_LINK_PATH} ${OCTAVE_LINK_PATHS}
)

IF(OCTAVE_EXECUTABLE AND OCTAVE_INCLUDE_DIR AND OCTAVE_LIBRARY)
  SET(OCTAVE_FOUND TRUE)
ELSE()
  SET(OCTAVE_FOUND FALSE)
ENDIF()
