# TRY TO FIND THE INCLUDE DIRECTORY
FIND_FILE(WORHP_LICENSE_KEY
worhp.lic
HINTS $ENV{WORHP} $ENV{WORHP_LICENSE_FILE}
)

IF (WORHP_LICENSE_KEY)
  MESSAGE(STATUS "Worhp license detected: ${WORHP_LICENSE_KEY}")
ELSE (WORHP_LICENSE_KEY)
  MESSAGE(STATUS "Could not find worhp license key, looking in $ENV{WORHP}")
ENDIF (WORHP_LICENSE_KEY)

FIND_PATH(WORHP_INCLUDE_DIR 
worhp.h
HINTS $ENV{WORHP}/include/worhp/
)

IF (WORHP_INCLUDE_DIR)
  MESSAGE(STATUS "Worhp include dir detected: ${WORHP_INCLUDE_DIR}")
ELSE (WORHP_INCLUDE_DIR)
  MESSAGE(STATUS "Could not find worhp include dir, looking in $ENV{WORHP}/include/worhp/")
ENDIF (WORHP_INCLUDE_DIR)

FIND_LIBRARY(WORHP_LIBRARY 
worhp
HINTS $ENV{WORHP}/lib/
)

IF (WORHP_LIBRARY)
  MESSAGE(STATUS "Worhp library detected: ${WORHP_LIBRARY}")
ELSE (WORHP_LIBRARY)
  MESSAGE(STATUS "Could not find worhp library, looking in $ENV{WORHP}/lib/" )
ENDIF (WORHP_LIBRARY)

SET(WORHP_LIBRARIES ${WORHP_LIBRARY})

SET(WORHP_LIBRARIES ${WORHP_LIBRARIES} ${LIBXML2_LIBRARIES})

SET(WORHP_LIBRARIES ${WORHP_LIBRARIES} ${COIN_METIS_LIBRARY})
IF (COIN_LAPACK_LIBRARY)
  SET(WORHP_LIBRARIES ${WORHP_LIBRARIES} ${COIN_LAPACK_LIBRARY} ${COIN_BLAS_LIBRARY})
ELSE(COIN_LAPACK_LIBRARY)
  IF (LAPACK_FOUND)
    set(WORHP_LIBRARIES ${WORHP_LIBRARIES} ${LAPACK_LIBRARIES})
  ELSE(LAPACK_FOUND)
    MESSAGE(STATUS "Lapack is missing. Could not find an independant version or a version packaged with Ipopt.")
  ENDIF(LAPACK_FOUND)
ENDIF(COIN_LAPACK_LIBRARY)

IF (WORHP_LIBRARY AND WORHP_INCLUDE_DIR)
  MESSAGE(STATUS "Worhp interface ready with these libraries: ${WORHP_LIBRARIES} ")
  SET(WORHP_FOUND TRUE)
ELSE (WORHP_LIBRARY AND WORHP_INCLUDE_DIR)
  MESSAGE(STATUS "Will not compile worhp interface")
ENDIF (WORHP_LIBRARY AND WORHP_INCLUDE_DIR)
