# TRY TO FIND THE INCLUDE DIRECTORY
FIND_PATH(ACADO_INCLUDE_DIR 
acado_toolkit.hpp
HINTS $ENV{ACADO}/include
)

IF (ACADO_INCLUDE_DIR)
  SET(FOUND_ACADO_INCLUDE TRUE)
  SET(ACADO_INCLUDE_DIRS 
  ${ACADO_INCLUDE_DIR} 
  ${ACADO_INCLUDE_DIR}/../external_packages 
  ${ACADO_INCLUDE_DIR}/../external_packages/qpOASES-2.0/INCLUDE
  ${ACADO_INCLUDE_DIR}/../new_features/include)
  MESSAGE(STATUS "Found ACADOtoolkit include dirs: ${ACADO_INCLUDE_DIRS}")
ELSE (ACADO_INCLUDE_DIR)
  MESSAGE(STATUS "Could not find ACADOtoolkit include dir")
ENDIF (ACADO_INCLUDE_DIR)

# TRY TO FIND THE LIBRARIES
SET(ACADO_LIBS_LIST
  acado_toolkit
  qpOASES2.0
  qpOASESextras2.0
  csparse)

SET(FOUND_ACADO_LIBS TRUE)
FOREACH(LIB ${ACADO_LIBS_LIST})
  FIND_LIBRARY(ACADO_LIB_${LIB}
    NAMES ${LIB}
    HINTS ${ACADO_INCLUDE_DIR}/../libs)
  IF(ACADO_LIB_${LIB})
    MESSAGE(STATUS "Found ${LIB}: ${ACADO_LIB_${LIB}}")
    SET(ACADO_LIBRARIES ${ACADO_LIBRARIES} ${ACADO_LIB_${LIB}})
  ELSE(ACADO_LIB_${LIB})
    SET(FOUND_ACADO_LIBS FALSE)
    MESSAGE(STATUS "Could not find lib${LIB}")
  ENDIF(ACADO_LIB_${LIB})
ENDFOREACH(LIB)

# print
IF(FOUND_ACADO_LIBS)
  MESSAGE(STATUS "Found ACADOtoolkit libraries: ${ACADO_LIBRARIES}")  
ELSEIF(FOUND_ACADO_INCLUDE AND FOUND_ACADO_LIBS)
  MESSAGE(STATUS "Cound not find ACADOtoolkit libraries")  
ENDIF(FOUND_ACADO_LIBS)

# SUCCESS IF BOTH THE LIBRARIES AND THE INCLUDE DIRECTORIES WERE FOUND
IF(FOUND_ACADO_INCLUDE AND FOUND_ACADO_LIBS)
  SET(FOUND_ACADO TRUE)
  MESSAGE(STATUS "Found ACADOtoolkit")  
ELSEIF(FOUND_ACADO_INCLUDE AND FOUND_ACADO_LIBS)
  MESSAGE(STATUS "Cound not find ACADOtoolkit")  
ENDIF(FOUND_ACADO_INCLUDE AND FOUND_ACADO_LIBS)
