find_package(LAPACK)

FIND_PATH(SUNDIALS_INCLUDE_DIR 
cvodes/cvodes.h
HINTS $ENV{SUNDIALS}/include
)

IF (SUNDIALS_INCLUDE_DIR)
   SET(FOUND_SUNDIALS_INCLUDE TRUE)
   MESSAGE(STATUS "Found SUNDIALS include dir: ${SUNDIALS_INCLUDE_DIR}")
ELSE (SUNDIALS_INCLUDE_DIR)
   MESSAGE(STATUS "Could not find SUNDIALS include dir")
ENDIF (SUNDIALS_INCLUDE_DIR)

FIND_LIBRARY(CVODES_LIBRARY
NAMES sundials_cvodes HINTS $ENV{SUNDIALS}/lib)

FIND_LIBRARY(IDAS_LIBRARY
NAMES sundials_idas HINTS $ENV{SUNDIALS}/lib)

FIND_LIBRARY(NVECSERIAL_LIBRARY
NAMES sundials_nvecserial HINTS $ENV{SUNDIALS}/lib)

IF (CVODES_LIBRARY AND IDAS_LIBRARY AND NVECSERIAL_LIBRARY)
   SET(FOUND_SUNDIALS_LIBS TRUE)
   SET(SUNDIALS_LIBRARIES ${CVODES_LIBRARY} ${IDAS_LIBRARY} ${NVECSERIAL_LIBRARY} ${LAPACK_LIBRARIES})


   MESSAGE(STATUS "Found SUNDIALS libs: ${SUNDIALS_LIBRARIES}")
ELSE (CVODES_LIBRARY AND IDAS_LIBRARY AND NVECSERIAL_LIBRARY)
   MESSAGE(STATUS "Could not find sundials libs")
ENDIF (CVODES_LIBRARY AND IDAS_LIBRARY AND NVECSERIAL_LIBRARY)


IF(FOUND_SUNDIALS_INCLUDE AND FOUND_SUNDIALS_LIBS)
  SET(FOUND_SUNDIALS TRUE)
ENDIF(FOUND_SUNDIALS_INCLUDE AND FOUND_SUNDIALS_LIBS)
