FIND_PATH(NUMPY_PATH
ndarrayobject.h
HINTS $ENV{NUMPY_INCLUDE}
PATHS ${PYTHON_INCLUDE_DIRS}/numpy ${PYTHON_INCLUDE_PATH}/numpy
)

FIND_PATH(NUMPY_PATH_DEP1
endian.h
)

STRING(REGEX REPLACE "include" "lib" NUMPY_LIBS_INTERMEDIATE "${NUMPY_PATH}")
STRING(REGEX REPLACE "numpy$" "" NUMPY_LIBS_BASE "${NUMPY_LIBS_INTERMEDIATE}")

FIND_LIBRARY(NUMPY_LIBS_1
NAMES multiarray multiarray.so
HINTS $ENV{NUMPY_LIBS}
PATHS ${NUMPY_LIBS_BASE}dist-packages/numpy/core)

SET(NUMPY_LIBS "${NUMPY_LIBS_1}")
SET(NUMPY_INCLUDED_DIRS "${NUMPY_PATH};${NUMPY_PATH_DEP1}")

IF(NUMPY_PATH)
SET(NUMPY_FOUND TRUE)
MESSAGE(STATUS "Numpy path found: ${NUMPY_PATH}")
MESSAGE(STATUS "Python libs: ${PYTHON_LIBRARIES}")
MESSAGE(STATUS "Numpy includes: ${NUMPY_INCLUDED_DIRS}")
MESSAGE(STATUS "Numpy libs: ${NUMPY_LIBS}")
ELSE()
MESSAGE(STATUS "Numpy not found")
ENDIF()
