# TRY TO FIND THE INCLUDE DIRECTORY
FIND_PATH(SQIC_INCLUDE_DIR 
sqic.mod
PATHS $ENV{SQIC_INCLUDE_DIR}
)

IF(NOT SQIC_INCLUDE_DIR )
  MESSAGE(STATUS "SQIC: Cound not find include dir. Try stetting SQIC_INCLUDE_DIR env var.") 
ENDIF(NOT SQIC_INCLUDE_DIR )

FIND_LIBRARY(SQIC_LIB_SNBLAS
snblas
PATHS $ENV{SQIC_LIBRARY_DIR}
)
IF(NOT SQIC_LIB_SNBLAS)
  MESSAGE(STATUS "SQIC: Cound not find library snblas. Try stetting SQIC_LIBRARY_DIR env var.") 
ENDIF(NOT SQIC_LIB_SNBLAS)


FIND_LIBRARY(SQIC_LIB_SQIC
sqic
PATHS $ENV{SQIC_LIBRARY_DIR}
)

IF(NOT SQIC_LIB_SQIC)
  MESSAGE(STATUS "SQIC: Cound not find library sqic. Try stetting SQIC_LIBRARY_DIR env var.") 
ENDIF(NOT SQIC_LIB_SQIC)

IF(SQIC_INCLUDE_DIR AND SQIC_LIB_SNBLAS AND SQIC_LIB_SQIC)
  SET(SQIC_LIBRARIES ${SQIC_LIB_SNBLAS} ${SQIC_LIB_SQIC})
  SET(SQIC_FOUND TRUE)
ENDIF(SQIC_INCLUDE_DIR AND SQIC_LIB_SNBLAS AND SQIC_LIB_SQIC)


