FIND_PATH(KNITRO_INCLUDE_DIR
knitro.h
HINTS $ENV{KNITRO}/include
)

IF (KNITRO_INCLUDE_DIR)
   SET(KNITRO_FOUND_INCLUDE TRUE)
   MESSAGE(STATUS "Found KNITRO include dir: ${KNITRO_INCLUDE_DIR}")
ELSE (KNITRO_INCLUDE_DIR)
   MESSAGE(STATUS "Could not find KNITRO include dir")
ENDIF (KNITRO_INCLUDE_DIR)

FIND_LIBRARY(KNITRO_LIBRARY NAMES knitro HINTS $ENV{KNITRO}/lib)

IF(KNITRO_LIBRARY)
  SET(KNITRO_LIBRARIES ${KNITRO_LIBRARY} ${CMAKE_DL_LIBS})
   MESSAGE(STATUS "Found KNITRO libraries: ${KNITRO_LIBRARIES}")
ELSE(KNITRO_LIBRARY)
   MESSAGE(STATUS "Could not find KNITRO library")
ENDIF(KNITRO_LIBRARY)

IF(KNITRO_FOUND_INCLUDE AND KNITRO_LIBRARIES)
  SET(KNITRO_FOUND TRUE)
ENDIF(KNITRO_FOUND_INCLUDE AND KNITRO_LIBRARIES)
