find_package(LAPACK)

FIND_PATH(SUNDIALS_INCLUDE_DIR 
cvodes/cvodes.h
HINTS $ENV{SUNDIALS}/include
)

IF (SUNDIALS_INCLUDE_DIR)
   SET(SUNDIALS_FOUND_INCLUDE TRUE)
   MESSAGE(STATUS "Found SUNDIALS include dir: ${SUNDIALS_INCLUDE_DIR}")
ELSE (SUNDIALS_INCLUDE_DIR)
   MESSAGE(STATUS "Could not find SUNDIALS include dir")
ENDIF (SUNDIALS_INCLUDE_DIR)

FIND_LIBRARY(CVODES_LIBRARY
NAMES sundials_cvodes HINTS $ENV{SUNDIALS}/lib)

FIND_LIBRARY(IDAS_LIBRARY
NAMES sundials_idas HINTS $ENV{SUNDIALS}/lib)

FIND_LIBRARY(KINSOL_LIBRARY
NAMES sundials_kinsol HINTS $ENV{SUNDIALS}/lib)

FIND_LIBRARY(NVECSERIAL_LIBRARY
NAMES sundials_nvecserial HINTS $ENV{SUNDIALS}/lib)

IF (CVODES_LIBRARY AND IDAS_LIBRARY AND KINSOL_LIBRARY AND NVECSERIAL_LIBRARY)
   SET(SUNDIALS_FOUND_LIBS TRUE)
   SET(SUNDIALS_LIBRARIES ${CVODES_LIBRARY} ${IDAS_LIBRARY} ${KINSOL_LIBRARY} ${NVECSERIAL_LIBRARY} ${LAPACK_LIBRARIES})
   MESSAGE(STATUS "Found SUNDIALS libs: ${SUNDIALS_LIBRARIES}")
ELSE (CVODES_LIBRARY AND IDAS_LIBRARY AND KINSOL_LIBRARY AND NVECSERIAL_LIBRARY)
   MESSAGE(STATUS "Could not find sundials libs")
ENDIF (CVODES_LIBRARY AND IDAS_LIBRARY AND KINSOL_LIBRARY AND NVECSERIAL_LIBRARY)

try_compile(WITH_SUNDIALS_2_5
  ${CMAKE_BINARY_DIR}
  ${CMAKE_SOURCE_DIR}/cmake_modules/check_sundials_version.cpp
  CMAKE_FLAGS 
    -DCOMPILE_DEFINITIONS:STRING=-DWITH_SUNDIALS_2_5
    -DINCLUDE_DIRECTORIES:STRING=${SUNDIALS_INCLUDE_DIR}
    -DLINK_LIBRARIES:STRING=${SUNDIALS_LIBRARIES}
  OUTPUT_VARIABLE OUTPUT)

if(WITH_SUNDIALS_2_5)
add_definitions(-DWITH_SUNDIALS_2_5)
endif(WITH_SUNDIALS_2_5)

IF(SUNDIALS_FOUND_INCLUDE AND SUNDIALS_FOUND_LIBS)
  SET(SUNDIALS_FOUND TRUE)
ENDIF(SUNDIALS_FOUND_INCLUDE AND SUNDIALS_FOUND_LIBS)
