#pragma once

#include <alpaqa/config/config.hpp>
#include <alpaqa/problem/box-constr-problem.hpp>
#include <alpaqa/util/copyable_unique_ptr.hpp>

#include <iosfwd>
#include <memory>
#include <string>

namespace alpaqa {

/// Wrapper for CUTEst problems loaded from an external shared library.
///
/// @warning  The lifetime of the wrapper should be at least as long as the
///           lifetime of the @ref CUTEstProblem::problem member. Do not make
///           a copy of the problem that could outlive the wrapper.
///
/// @ingroup  grp_ExternalProblemLoaders
class CUTEstProblem : public BoxConstrProblem<alpaqa::DefaultConfig> {
  public:
    USING_ALPAQA_CONFIG(alpaqa::DefaultConfig);

    /// Load a CUTEst problem from the given shared library and OUTSDIF.d file.
    CUTEstProblem(const char *so_fname, const char *outsdif_fname);
    /// @copydoc CUTEstProblem::CUTEstProblem(const char*, const char *)
    CUTEstProblem(const std::string &so_fname,
                  const std::string &outsdif_fname);
    CUTEstProblem(const CUTEstProblem &);
    CUTEstProblem &operator=(const CUTEstProblem &);
    CUTEstProblem(CUTEstProblem &&) noexcept;
    CUTEstProblem &operator=(CUTEstProblem &&) noexcept;
    ~CUTEstProblem();

  public:
    /// The report generated by CUTEst.
    ///
    /// @see `man CUTEST_creport` and `man CUTEST_ureport`
    struct Report {
        /// Name of the problem.
        std::string name;

        /// Number of independent variables.
        int nvar = 0;
        /// Number of constraints.
        int ncon = 0;

        /// Status returned by CUTEst.
        /// @todo   I don't think this is useful, remove it.
        enum Status {
            Success         = 0,    ///< Successful call.
            AllocationError = 1,    ///< Array allocation/deallocation error.
            ArrayBoundError = 2,    ///< Array bound error.
            EvaluationError = 3,    ///< Evaluation error.
        } status = Status::Success; ///< Exit status.

        /// Function call counters.
        ///
        /// @note   Note that hessian_times_vector, constraints and constraints_grad
        ///         may account for codes which allow the evaluation of a
        ///         selection of constraints only and may thus be much smaller
        ///         than the number of constraints times the number of
        ///         iterations.
        struct {
            /// Number of calls to the objective function.
            unsigned objective = 0;
            /// Number of calls to the objective gradient.
            unsigned objective_grad = 0;
            /// Number of calls to the objective Hessian.
            unsigned objective_hess = 0;
            /// Number of Hessian times vector products.
            unsigned hessian_times_vector = 0;
            /// Number of calls to the constraint functions.
            unsigned constraints = 0;
            /// Number of calls to the constraint gradients.
            unsigned constraints_grad = 0;
            /// Number of calls to the constraint Hessians.
            unsigned constraints_hess = 0;
        } calls; ///< Function call counters.

        /// CPU time (in seconds) for CUTEST_csetup.
        double time_setup = 0;
        /// CPU time (in seconds) since the end of CUTEST_csetup.
        double time = 0;
    };

    [[nodiscard]] Report get_report() const;

  public:
    std::string name = "<UNKNOWN>"; ///< Problem name
    vec x0;                         ///< Initial value of decision variables
    vec y0;                         ///< Initial value of Lagrange multipliers

  private:
    util::copyable_unique_ptr<class CUTEstLoader> impl;

  public:
    [[nodiscard]] real_t eval_f(crvec x) const;
    void eval_grad_f(crvec x, rvec grad_fx) const;
    void eval_g(crvec x, rvec gx) const;
    void eval_grad_g_prod(crvec x, crvec y, rvec grad_gxy) const;

    void eval_jac_g(crvec x, rindexvec inner_idx, rindexvec outer_ptr,
                    rvec J_values) const;
    [[nodiscard]] length_t get_jac_g_num_nonzeros() const;
    void eval_grad_gi(crvec x, index_t i, rvec grad_gi) const;
    void eval_hess_L_prod(crvec x, crvec y, real_t scale, crvec v,
                          rvec Hv) const;
    void eval_hess_L(crvec x, crvec y, real_t scale, rindexvec inner_idx,
                     rindexvec outer_ptr, rvec H_values) const;
    [[nodiscard]] length_t get_hess_L_num_nonzeros() const;
    [[nodiscard]] real_t eval_f_grad_f(crvec x, rvec grad_fx) const;
    [[nodiscard]] real_t eval_f_g(crvec x, rvec g) const;
    void eval_grad_L(crvec x, crvec y, rvec grad_L, rvec work_n) const;
};

/// @related    CUTEstProblem::Report
std::ostream &operator<<(std::ostream &, const CUTEstProblem::Report &);
/// @related    CUTEstProblem::Report::Status
const char *enum_name(CUTEstProblem::Report::Status);
/// @related    CUTEstProblem::Report::Status
std::ostream &operator<<(std::ostream &, CUTEstProblem::Report::Status);

} // namespace alpaqa