# Match the normal plugin registry against Wasm recipes at configure time.
function(wasmjs_register_plugin kind name)
  set_property(GLOBAL APPEND PROPERTY CASADI_WASM_PLUGINS "${kind}::${name}")
endfunction()

function(wasmjs_exclude_plugin kind name reason)
  if("${reason}" STREQUAL "")
    message(FATAL_ERROR "A Wasm plugin exclusion requires a reason")
  endif()
  set_property(GLOBAL APPEND PROPERTY CASADI_WASM_EXCLUDED "${kind}::${name}")
  set_property(GLOBAL PROPERTY "CASADI_WASM_REASON_${kind}::${name}" "${reason}")
endfunction()

function(wasmjs_write_manifest output)
  get_property(_configured GLOBAL PROPERTY CASADI_PLUGINS)
  if(NOT _configured)
    message(FATAL_ERROR "Finalize Wasm plugins after the normal plugin registry is populated")
  endif()
  get_property(_shipped GLOBAL PROPERTY CASADI_WASM_PLUGINS)
  get_property(_excluded GLOBAL PROPERTY CASADI_WASM_EXCLUDED)
  set(_entries "")
  foreach(_plugin IN LISTS _configured)
    string(TOLOWER "${_plugin}" _id)
    string(REPLACE "::" ";" _parts "${_id}")
    list(GET _parts 0 _kind)
    list(GET _parts 1 _name)
    if(_id IN_LIST _shipped AND _id IN_LIST _excluded)
      message(FATAL_ERROR "Wasm plugin ${_id} is both shipped and excluded")
    elseif(_id IN_LIST _shipped)
      list(APPEND _entries "    {\"kind\":\"${_kind}\",\"name\":\"${_name}\",\"file\":\"libcasadi_${_kind}_${_name}.so\"}")
    elseif(_id IN_LIST _excluded)
      get_property(_reason GLOBAL PROPERTY "CASADI_WASM_REASON_${_id}")
      string(REPLACE "\\" "\\\\" _reason "${_reason}")
      string(REPLACE "\"" "\\\"" _reason "${_reason}")
      string(REPLACE ";" "\\u003b" _reason "${_reason}")
      string(REPLACE "\n" "\\n" _reason "${_reason}")
      string(REPLACE "\r" "\\r" _reason "${_reason}")
      string(REPLACE "\t" "\\t" _reason "${_reason}")
      list(APPEND _entries "    {\"kind\":\"${_kind}\",\"name\":\"${_name}\",\"excluded\":\"${_reason}\"}")
    else()
      message(FATAL_ERROR "Enabled plugin ${_id} has no Wasm side-module recipe. Add wasmjs_side_plugin() or wasmjs_exclude_plugin() with a reason.")
    endif()
  endforeach()
  string(REPLACE ";" ",\n" _entries "${_entries}")
  file(WRITE "${output}" "{\n  \"plugins\": [\n${_entries}\n  ]\n}\n")
endfunction()
