/*
 *    This file is part of CasADi.
 *
 *    CasADi -- A symbolic framework for dynamic optimization.
 *    Copyright (C) 2010 by Joel Andersson, Moritz Diehl, K.U.Leuven. All rights reserved.
 *
 *    CasADi is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    CasADi is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with CasADi; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


      #include "dsdp_internal.hpp"
      #include <string>

      const std::string casadi::DSDPInternal::meta_doc=
      "\n"
"\n"
">List of available options\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"|       Id        |      Type       |     Default     |   Description   |\n"
"+=================+=================+=================+=================+\n"
"| _loglevel       | OT_INTEGER      | 0               | An integer that |\n"
"|                 |                 |                 | specifies how   |\n"
"|                 |                 |                 | much logging is |\n"
"|                 |                 |                 | done on stdout. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| _penalty        | OT_REAL         | 100000          | Penality        |\n"
"|                 |                 |                 | parameter       |\n"
"|                 |                 |                 | lambda. Must    |\n"
"|                 |                 |                 | exceed the      |\n"
"|                 |                 |                 | trace of Y.     |\n"
"|                 |                 |                 | This parameter  |\n"
"|                 |                 |                 | heavily         |\n"
"|                 |                 |                 | influences the  |\n"
"|                 |                 |                 | ability of DSDP |\n"
"|                 |                 |                 | to treat linear |\n"
"|                 |                 |                 | equalities. The |\n"
"|                 |                 |                 | DSDP standard   |\n"
"|                 |                 |                 | default (1e8)   |\n"
"|                 |                 |                 | will make a     |\n"
"|                 |                 |                 | problem with    |\n"
"|                 |                 |                 | linear equality |\n"
"|                 |                 |                 | return unusable |\n"
"|                 |                 |                 | solutions.      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| _printlevel     | OT_INTEGER      | 1               | A printlevel of |\n"
"|                 |                 |                 | zero will       |\n"
"|                 |                 |                 | disable all     |\n"
"|                 |                 |                 | output. Another |\n"
"|                 |                 |                 | number          |\n"
"|                 |                 |                 | indicates how   |\n"
"|                 |                 |                 | often a line is |\n"
"|                 |                 |                 | printed.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| _reuse          | OT_INTEGER      | 4               | Maximum on the  |\n"
"|                 |                 |                 | number of times |\n"
"|                 |                 |                 | the Schur       |\n"
"|                 |                 |                 | complement      |\n"
"|                 |                 |                 | matrix is       |\n"
"|                 |                 |                 | reused          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| _rho            | OT_REAL         | 4               | Potential       |\n"
"|                 |                 |                 | parameter. Must |\n"
"|                 |                 |                 | be >=1          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| _use_penalty    | OT_BOOLEAN      | true            | Modifies the    |\n"
"|                 |                 |                 | algorithm to    |\n"
"|                 |                 |                 | use a penality  |\n"
"|                 |                 |                 | gamma on r.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| _zbar           | OT_REAL         | 1.000e+10       | Initial upper   |\n"
"|                 |                 |                 | bound on the    |\n"
"|                 |                 |                 | objective of    |\n"
"|                 |                 |                 | the dual        |\n"
"|                 |                 |                 | problem.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| ad_mode         | OT_STRING       | \"automatic\"     | How to          |\n"
"|                 |                 |                 | calculate the   |\n"
"|                 |                 |                 | Jacobians.      |\n"
"|                 |                 |                 | (forward: only  |\n"
"|                 |                 |                 | forward         |\n"
"|                 |                 |                 | mode|reverse:   |\n"
"|                 |                 |                 | only adjoint    |\n"
"|                 |                 |                 | mode|automatic: |\n"
"|                 |                 |                 | a heuristic     |\n"
"|                 |                 |                 | decides which   |\n"
"|                 |                 |                 | is more         |\n"
"|                 |                 |                 | appropriate)    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| calc_dual       | OT_BOOLEAN      | true            | Indicate if     |\n"
"|                 |                 |                 | dual should be  |\n"
"|                 |                 |                 | allocated and   |\n"
"|                 |                 |                 | calculated. You |\n"
"|                 |                 |                 | may want to     |\n"
"|                 |                 |                 | avoid           |\n"
"|                 |                 |                 | calculating     |\n"
"|                 |                 |                 | this variable   |\n"
"|                 |                 |                 | for problems    |\n"
"|                 |                 |                 | with n large,   |\n"
"|                 |                 |                 | as is always    |\n"
"|                 |                 |                 | dense (m x m).  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| calc_p          | OT_BOOLEAN      | true            | Indicate if the |\n"
"|                 |                 |                 | P-part of       |\n"
"|                 |                 |                 | primal solution |\n"
"|                 |                 |                 | should be       |\n"
"|                 |                 |                 | allocated and   |\n"
"|                 |                 |                 | calculated. You |\n"
"|                 |                 |                 | may want to     |\n"
"|                 |                 |                 | avoid           |\n"
"|                 |                 |                 | calculating     |\n"
"|                 |                 |                 | this variable   |\n"
"|                 |                 |                 | for problems    |\n"
"|                 |                 |                 | with n large,   |\n"
"|                 |                 |                 | as is always    |\n"
"|                 |                 |                 | dense (m x m).  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| derivative_gene | OT_DERIVATIVEGE | GenericType()   | Function that   |\n"
"| rator           | NERATOR         |                 | returns a       |\n"
"|                 |                 |                 | derivative      |\n"
"|                 |                 |                 | function given  |\n"
"|                 |                 |                 | a number of     |\n"
"|                 |                 |                 | forward and     |\n"
"|                 |                 |                 | reverse         |\n"
"|                 |                 |                 | directional     |\n"
"|                 |                 |                 | derivative,     |\n"
"|                 |                 |                 | overrides       |\n"
"|                 |                 |                 | internal        |\n"
"|                 |                 |                 | routines. Check |\n"
"|                 |                 |                 | documentation   |\n"
"|                 |                 |                 | of DerivativeGe |\n"
"|                 |                 |                 | nerator.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| dualTol         | OT_REAL         | 0.000           | Tolerance for   |\n"
"|                 |                 |                 | dual            |\n"
"|                 |                 |                 | infeasibility   |\n"
"|                 |                 |                 | (translates to  |\n"
"|                 |                 |                 | primal          |\n"
"|                 |                 |                 | infeasibility   |\n"
"|                 |                 |                 | in dsdp terms)  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gapTol          | OT_REAL         | 0.000           | Convergence     |\n"
"|                 |                 |                 | criterion based |\n"
"|                 |                 |                 | on distance     |\n"
"|                 |                 |                 | between primal  |\n"
"|                 |                 |                 | and dual        |\n"
"|                 |                 |                 | objective       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gather_stats    | OT_BOOLEAN      | false           | Flag to         |\n"
"|                 |                 |                 | indicate        |\n"
"|                 |                 |                 | whether         |\n"
"|                 |                 |                 | statistics must |\n"
"|                 |                 |                 | be gathered     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| inf             | OT_REAL         | 1.000e+30       | Treat numbers   |\n"
"|                 |                 |                 | higher than     |\n"
"|                 |                 |                 | this as         |\n"
"|                 |                 |                 | infinity        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| inputs_check    | OT_BOOLEAN      | true            | Throw           |\n"
"|                 |                 |                 | exceptions when |\n"
"|                 |                 |                 | the numerical   |\n"
"|                 |                 |                 | values of the   |\n"
"|                 |                 |                 | inputs don't    |\n"
"|                 |                 |                 | make sense      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| maxIter         | OT_INTEGER      | 500             | Maximum number  |\n"
"|                 |                 |                 | of iterations   |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| monitor         | OT_STRINGVECTOR | GenericType()   | Monitors to be  |\n"
"|                 |                 |                 | activated (inpu |\n"
"|                 |                 |                 | ts|outputs)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| name            | OT_STRING       | \"unnamed_shared | name of the     |\n"
"|                 |                 | _object\"        | object          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| primalTol       | OT_REAL         | 0.000           | Tolerance for   |\n"
"|                 |                 |                 | primal          |\n"
"|                 |                 |                 | infeasibility   |\n"
"|                 |                 |                 | (translates to  |\n"
"|                 |                 |                 | dual            |\n"
"|                 |                 |                 | infeasibility   |\n"
"|                 |                 |                 | in dsdp terms)  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| print_problem   | OT_BOOLEAN      | false           | Print out       |\n"
"|                 |                 |                 | problem         |\n"
"|                 |                 |                 | statement for   |\n"
"|                 |                 |                 | debugging.      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| regularity_chec | OT_BOOLEAN      | true            | Throw           |\n"
"| k               |                 |                 | exceptions when |\n"
"|                 |                 |                 | NaN or Inf      |\n"
"|                 |                 |                 | appears during  |\n"
"|                 |                 |                 | evaluation      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| stepTol         | OT_REAL         | 0.050           | Terminate the   |\n"
"|                 |                 |                 | solver if the   |\n"
"|                 |                 |                 | step length in  |\n"
"|                 |                 |                 | the primal is   |\n"
"|                 |                 |                 | below this      |\n"
"|                 |                 |                 | tolerance.      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| user_data       | OT_VOIDPTR      | GenericType()   | A user-defined  |\n"
"|                 |                 |                 | field that can  |\n"
"|                 |                 |                 | be used to      |\n"
"|                 |                 |                 | identify the    |\n"
"|                 |                 |                 | function or     |\n"
"|                 |                 |                 | pass additional |\n"
"|                 |                 |                 | information     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| verbose         | OT_BOOLEAN      | false           | Verbose         |\n"
"|                 |                 |                 | evaluation  for |\n"
"|                 |                 |                 | debugging       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"\n"
"\n"
">List of available stats\n"
"+--------------------+\n"
"|         Id         |\n"
"+====================+\n"
"| solution_type      |\n"
"+--------------------+\n"
"| termination_reason |\n"
"+--------------------+\n"
"\n"
"\n"
"\n"
"\n"
;
