usr/lib/libcasadi_implicitfunction_newton.so.*
usr/lib/libcasadi_implicitfunction_newton.so
usr/lib/libcasadi_implicitfunction_nlp.so.*
usr/lib/libcasadi_implicitfunction_nlp.so

usr/lib/libcasadi_integrator_collocation.so.*
usr/lib/libcasadi_integrator_collocation.so
usr/lib/libcasadi_integrator_rk.so.*
usr/lib/libcasadi_integrator_rk.so

usr/lib/libcasadi_linearsolver_symbolicqr.so.*
usr/lib/libcasadi_linearsolver_symbolicqr.so
usr/lib/libcasadi_lpsolver_qp.so.*
usr/lib/libcasadi_lpsolver_qp.so

usr/lib/libcasadi_qpsolver_nlp.so.*
usr/lib/libcasadi_qpsolver_nlp.so
usr/lib/libcasadi_qpsolver_qcqp.so.*
usr/lib/libcasadi_qpsolver_qcqp.so


usr/lib/libcasadi_socpsolver_sdp.so.*
usr/lib/libcasadi_socpsolver_sdp.so
usr/lib/libcasadi_dplesolver_simple.so.*
usr/lib/libcasadi_dplesolver_simple.so

usr/lib/libcasadi_stabilizedqpsolver_qp.so.*
usr/lib/libcasadi_stabilizedqpsolver_qp.so

# these need cholesky right now:
#usr/lib/libcasadi_qcqpsolver_socp.so.*
#usr/lib/libcasadi_qcqpsolver_socp.so
#usr/lib/libcasadi_sdqpsolver_sdp.so.*
#usr/lib/libcasadi_sdqpsolver_sdp.so

# these aren't ready for outside use as far as I know:
#usr/lib/libcasadi_nlpsolver_sqpmethod.so.*
#usr/lib/libcasadi_nlpsolver_sqpmethod.so
#usr/lib/libcasadi_homotopynlpsolver_simple.so.*
#usr/lib/libcasadi_homotopynlpsolver_simple.so
#usr/lib/libcasadi_nlpsolver_stabilizedsqp.so.*
#usr/lib/libcasadi_nlpsolver_stabilizedsqp.so
#usr/lib/libcasadi_nlpsolver_scpgen.so.*
#usr/lib/libcasadi_nlpsolver_scpgen.so
