// NOLINT(legal/copyright)
const char* casadi_version = "${PACKAGE_VERSION}";  // NOLINT(whitespace/line_length)
const char* casadi_git_revision = "${git_revision}";  // NOLINT(whitespace/line_length)
const char* casadi_git_describe = "${git_describe}";  // NOLINT(whitespace/line_length)
const char* casadi_feature_list = "${feature_list}";  // NOLINT(whitespace/line_length)
const char* casadi_build_type = "${CMAKE_BUILD_TYPE}";  // NOLINT(whitespace/line_length)
const char* casadi_compiler_id = "${CMAKE_CXX_COMPILER_ID}";  // NOLINT(whitespace/line_length)
const char* casadi_compiler = "${CMAKE_CXX_COMPILER}";  // NOLINT(whitespace/line_length)
const char* casadi_compiler_flags ="${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_${UPPER_CMAKE_BUILD_TYPE}} ${EXTRA_CXX_FLAGS_FROM_DEFS}";  // NOLINT(whitespace/line_length)
const char* casadi_modules ="${CASADI_MODULES}";  // NOLINT(whitespace/line_length)
const char* casadi_plugins ="${CASADI_PLUGINS}";  // NOLINT(whitespace/line_length)
const char* casadi_install_prefix ="${CMAKE_INSTALL_PREFIX}";  // NOLINT(whitespace/line_length)
