#!/bin/sh

echo " "
echo "Downloading AMPL source files for the CUTEr test suite"
echo " "

wget -e robots=off -r -l1 --no-parent -A.mod http://orfe.princeton.edu/~rvdb/ampl/nlmodels/cute/
mv orfe.princeton.edu/~rvdb/ampl/nlmodels/cute/*.mod .
rm -rf orfe.princeton.edu

echo " "
echo "Done downloading cuter"
echo " "
