#include "bisection.hpp"
#include <string>

const std::string casadi::Bisection::meta_doc =
    "\n"
    "Bisection method for scalar rootfinding.\n"
    "\n"
    "Finds x such that f(x, p) = 0 by repeatedly halving a bracket [a, b]\n"
    "that is known to contain a sign change of f.\n"
    "\n"
    "Requirements:\n"
    "  * The function f must be scalar (n=1).\n"
    "\n"
    "Options:\n"
    "  max_iter     : Maximum number of iterations              (default 100)\n"
    "  max_search   : Maximum number of search bracket          (default 100)\n"
    "  abstol_step  : Absolute tolerance on bracket width       (default 1e-9)\n"
    "  abstol       : Absolute tolerance of residual            (default 1e-9)\n"
    "  lb           : Lower bound of initial bracket            (default -1e12)\n"
    "  ub           : Upper bound of initial bracket            (default  1e12)\n"
    "  search_step  : Step size for bracket searching          (default  1.0)\n"
    "\n"
    "Convergence: The iteration stops when either\n"
    "  (b - a) < abstol_step  OR  |f(mid)| < abstol\n"
    "\n"
    ">List of available options\n"
    "\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| Id             | Type      | Description                                 |\n"
    "+===========+==========+===================================================+\n"
    "| max_iter       | OT_INT    | Maximum number of bisection iterations      |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| abstol_step    | OT_DOUBLE | Absolute tolerance on bracket width         |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| abstol         | OT_DOUBLE | Absolute tolerance of residual              |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| lb             | OT_DOUBLE | Lower bound of the initial bracket          |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| ub             | OT_DOUBLE | Upper bound of the initial bracket          |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| search_step    | OT_DOUBLE | Step size for bracket searching             |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "| max_search     | OT_INT    | Maximum number of iterations                |\n"
    "+-----------+----------+---------------------------------------------------+\n"
    "\n";