/*
 *    This file is part of CasADi.
 *
 *    CasADi -- A symbolic framework for dynamic optimization.
 *    Copyright (C) 2010 by Joel Andersson, Moritz Diehl, K.U.Leuven. All rights reserved.
 *
 *    CasADi is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *
 *    CasADi is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with CasADi; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */


      #include "stabilized_sqp_internal.hpp"
      #include <string>

      const std::string casadi::StabilizedSQPInternal::meta_doc=
      "\n"
"\n"
">List of available options\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"|       Id        |      Type       |     Default     |   Description   |\n"
"+=================+=================+=================+=================+\n"
"| TReta1          | OT_REAL         | 0.800           | Required        |\n"
"|                 |                 |                 | predicted /     |\n"
"|                 |                 |                 | actual decrease |\n"
"|                 |                 |                 | for TR increase |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| TReta2          | OT_REAL         | 0.200           | Required        |\n"
"|                 |                 |                 | predicted /     |\n"
"|                 |                 |                 | actual decrease |\n"
"|                 |                 |                 | for TR decrease |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| ad_mode         | OT_STRING       | \"automatic\"     | How to          |\n"
"|                 |                 |                 | calculate the   |\n"
"|                 |                 |                 | Jacobians.      |\n"
"|                 |                 |                 | (forward: only  |\n"
"|                 |                 |                 | forward         |\n"
"|                 |                 |                 | mode|reverse:   |\n"
"|                 |                 |                 | only adjoint    |\n"
"|                 |                 |                 | mode|automatic: |\n"
"|                 |                 |                 | a heuristic     |\n"
"|                 |                 |                 | decides which   |\n"
"|                 |                 |                 | is more         |\n"
"|                 |                 |                 | appropriate)    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| alphaMin        | OT_REAL         | 0.001           | Used to check   |\n"
"|                 |                 |                 | whether to      |\n"
"|                 |                 |                 | increase rho.   |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| beta            | OT_REAL         | 0.500           | Line-search     |\n"
"|                 |                 |                 | parameter,      |\n"
"|                 |                 |                 | restoration     |\n"
"|                 |                 |                 | factor of       |\n"
"|                 |                 |                 | stepsize        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| c1              | OT_REAL         | 0.001           | Armijo          |\n"
"|                 |                 |                 | condition,      |\n"
"|                 |                 |                 | coefficient of  |\n"
"|                 |                 |                 | decrease in     |\n"
"|                 |                 |                 | merit           |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| derivative_gene | OT_DERIVATIVEGE | GenericType()   | Function that   |\n"
"| rator           | NERATOR         |                 | returns a       |\n"
"|                 |                 |                 | derivative      |\n"
"|                 |                 |                 | function given  |\n"
"|                 |                 |                 | a number of     |\n"
"|                 |                 |                 | forward and     |\n"
"|                 |                 |                 | reverse         |\n"
"|                 |                 |                 | directional     |\n"
"|                 |                 |                 | derivative,     |\n"
"|                 |                 |                 | overrides       |\n"
"|                 |                 |                 | internal        |\n"
"|                 |                 |                 | routines. Check |\n"
"|                 |                 |                 | documentation   |\n"
"|                 |                 |                 | of DerivativeGe |\n"
"|                 |                 |                 | nerator.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| dvMax0          | OT_REAL         | 100             | Parameter used  |\n"
"|                 |                 |                 | to defined the  |\n"
"|                 |                 |                 | max step        |\n"
"|                 |                 |                 | length.         |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| eps_active      | OT_REAL         | 0.000           | Threshold for   |\n"
"|                 |                 |                 | the epsilon-    |\n"
"|                 |                 |                 | active set.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| eval_errors_fat | OT_BOOLEAN      | false           | When errors     |\n"
"| al              |                 |                 | occur during    |\n"
"|                 |                 |                 | evaluation of   |\n"
"|                 |                 |                 | f,g,...,stop    |\n"
"|                 |                 |                 | the iterations  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| expand          | OT_BOOLEAN      | false           | Expand the NLP  |\n"
"|                 |                 |                 | function in     |\n"
"|                 |                 |                 | terms of scalar |\n"
"|                 |                 |                 | operations,     |\n"
"|                 |                 |                 | i.e. MX->SX     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gamma1          | OT_REAL         | 2               | Trust region    |\n"
"|                 |                 |                 | increase        |\n"
"|                 |                 |                 | parameter       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gamma2          | OT_REAL         | 1               | Trust region    |\n"
"|                 |                 |                 | update          |\n"
"|                 |                 |                 | parameter       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gamma3          | OT_REAL         | 1               | Trust region    |\n"
"|                 |                 |                 | decrease        |\n"
"|                 |                 |                 | parameter       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| gather_stats    | OT_BOOLEAN      | false           | Flag to         |\n"
"|                 |                 |                 | indicate        |\n"
"|                 |                 |                 | whether         |\n"
"|                 |                 |                 | statistics must |\n"
"|                 |                 |                 | be gathered     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| grad_f          | OT_FUNCTION     | GenericType()   | Function for    |\n"
"|                 |                 |                 | calculating the |\n"
"|                 |                 |                 | gradient of the |\n"
"|                 |                 |                 | objective       |\n"
"|                 |                 |                 | (column,        |\n"
"|                 |                 |                 | autogenerated   |\n"
"|                 |                 |                 | by default)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| grad_lag        | OT_FUNCTION     | GenericType()   | Function for    |\n"
"|                 |                 |                 | calculating the |\n"
"|                 |                 |                 | gradient of the |\n"
"|                 |                 |                 | Lagrangian      |\n"
"|                 |                 |                 | (autogenerated  |\n"
"|                 |                 |                 | by default)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| hess_lag        | OT_FUNCTION     | GenericType()   | Function for    |\n"
"|                 |                 |                 | calculating the |\n"
"|                 |                 |                 | Hessian of the  |\n"
"|                 |                 |                 | Lagrangian      |\n"
"|                 |                 |                 | (autogenerated  |\n"
"|                 |                 |                 | by default)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| hessian_approxi | OT_STRING       | \"exact\"         | limited-        |\n"
"| mation          |                 |                 | memory|exact    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| ignore_check_ve | OT_BOOLEAN      | false           | If set to true, |\n"
"| c               |                 |                 | the input shape |\n"
"|                 |                 |                 | of F will not   |\n"
"|                 |                 |                 | be checked.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| inputs_check    | OT_BOOLEAN      | true            | Throw           |\n"
"|                 |                 |                 | exceptions when |\n"
"|                 |                 |                 | the numerical   |\n"
"|                 |                 |                 | values of the   |\n"
"|                 |                 |                 | inputs don't    |\n"
"|                 |                 |                 | make sense      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| iteration_callb | OT_CALLBACK     | GenericType()   | A function that |\n"
"| ack             |                 |                 | will be called  |\n"
"|                 |                 |                 | at each         |\n"
"|                 |                 |                 | iteration with  |\n"
"|                 |                 |                 | the solver as   |\n"
"|                 |                 |                 | input. Check    |\n"
"|                 |                 |                 | documentation   |\n"
"|                 |                 |                 | of Callback.    |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| iteration_callb | OT_BOOLEAN      | false           | If set to true, |\n"
"| ack_ignore_erro |                 |                 | errors thrown   |\n"
"| rs              |                 |                 | by iteration_ca |\n"
"|                 |                 |                 | llback will be  |\n"
"|                 |                 |                 | ignored.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| iteration_callb | OT_INTEGER      | 1               | Only call the   |\n"
"| ack_step        |                 |                 | callback        |\n"
"|                 |                 |                 | function every  |\n"
"|                 |                 |                 | few iterations. |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| jac_f           | OT_FUNCTION     | GenericType()   | Function for    |\n"
"|                 |                 |                 | calculating the |\n"
"|                 |                 |                 | jacobian of the |\n"
"|                 |                 |                 | objective       |\n"
"|                 |                 |                 | (sparse row,    |\n"
"|                 |                 |                 | autogenerated   |\n"
"|                 |                 |                 | by default)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| jac_g           | OT_FUNCTION     | GenericType()   | Function for    |\n"
"|                 |                 |                 | calculating the |\n"
"|                 |                 |                 | Jacobian of the |\n"
"|                 |                 |                 | constraints     |\n"
"|                 |                 |                 | (autogenerated  |\n"
"|                 |                 |                 | by default)     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| lbfgs_memory    | OT_INTEGER      | 10              | Size of L-BFGS  |\n"
"|                 |                 |                 | memory.         |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| max_iter        | OT_INTEGER      | 100             | Maximum number  |\n"
"|                 |                 |                 | of SQP          |\n"
"|                 |                 |                 | iterations      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| max_iter_ls     | OT_INTEGER      | 20              | Maximum number  |\n"
"|                 |                 |                 | of linesearch   |\n"
"|                 |                 |                 | iterations      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| max_time        | OT_REAL         | 1.000e+12       | Timeout         |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| merit_memory    | OT_INTEGER      | 4               | Size of memory  |\n"
"|                 |                 |                 | to store        |\n"
"|                 |                 |                 | history of      |\n"
"|                 |                 |                 | merit function  |\n"
"|                 |                 |                 | values          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| min_step_size   | OT_REAL         | 0.000           | The size (inf-  |\n"
"|                 |                 |                 | norm) of the    |\n"
"|                 |                 |                 | step size       |\n"
"|                 |                 |                 | should not      |\n"
"|                 |                 |                 | become smaller  |\n"
"|                 |                 |                 | than this.      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| monitor         | OT_STRINGVECTOR | GenericType()   | Monitors to be  |\n"
"|                 |                 |                 | activated (inpu |\n"
"|                 |                 |                 | ts|outputs)  (e |\n"
"|                 |                 |                 | val_f|eval_g|ev |\n"
"|                 |                 |                 | al_jac_g|eval_g |\n"
"|                 |                 |                 | rad_f|eval_h|qp |\n"
"|                 |                 |                 | |dx)            |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| muR0            | OT_REAL         | 0.000           | Initial choice  |\n"
"|                 |                 |                 | of              |\n"
"|                 |                 |                 | regularization  |\n"
"|                 |                 |                 | parameter       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| name            | OT_STRING       | \"unnamed_shared | name of the     |\n"
"|                 |                 | _object\"        | object          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| nu              | OT_REAL         | 1               | Parameter for   |\n"
"|                 |                 |                 | primal-dual     |\n"
"|                 |                 |                 | augmented       |\n"
"|                 |                 |                 | Lagrangian.     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| phiWeight       | OT_REAL         | 0.000           | Weight used in  |\n"
"|                 |                 |                 | pseudo-filter.  |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| print_header    | OT_BOOLEAN      | true            | Print the       |\n"
"|                 |                 |                 | header with     |\n"
"|                 |                 |                 | problem         |\n"
"|                 |                 |                 | statistics      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| regularity_chec | OT_BOOLEAN      | true            | Throw           |\n"
"| k               |                 |                 | exceptions when |\n"
"|                 |                 |                 | NaN or Inf      |\n"
"|                 |                 |                 | appears during  |\n"
"|                 |                 |                 | evaluation      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| regularize      | OT_BOOLEAN      | false           | Automatic       |\n"
"|                 |                 |                 | regularization  |\n"
"|                 |                 |                 | of Lagrange     |\n"
"|                 |                 |                 | Hessian.        |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| stabilized_qp_s | OT_STRING       | GenericType()   | The Stabilized  |\n"
"| olver           |                 |                 | QP solver to be |\n"
"|                 |                 |                 | used by the SQP |\n"
"|                 |                 |                 | method          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| stabilized_qp_s | OT_DICTIONARY   | GenericType()   | Options to be   |\n"
"| olver_options   |                 |                 | passed to the   |\n"
"|                 |                 |                 | Stabilized QP   |\n"
"|                 |                 |                 | solver          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| tau0            | OT_REAL         | 0.010           | Initial         |\n"
"|                 |                 |                 | parameter for   |\n"
"|                 |                 |                 | the merit       |\n"
"|                 |                 |                 | function        |\n"
"|                 |                 |                 | optimality      |\n"
"|                 |                 |                 | threshold.      |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| tol_du          | OT_REAL         | 0.000           | Stopping        |\n"
"|                 |                 |                 | criterion for   |\n"
"|                 |                 |                 | dual            |\n"
"|                 |                 |                 | infeasability   |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| tol_pr          | OT_REAL         | 0.000           | Stopping        |\n"
"|                 |                 |                 | criterion for   |\n"
"|                 |                 |                 | primal          |\n"
"|                 |                 |                 | infeasibility   |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| user_data       | OT_VOIDPTR      | GenericType()   | A user-defined  |\n"
"|                 |                 |                 | field that can  |\n"
"|                 |                 |                 | be used to      |\n"
"|                 |                 |                 | identify the    |\n"
"|                 |                 |                 | function or     |\n"
"|                 |                 |                 | pass additional |\n"
"|                 |                 |                 | information     |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| verbose         | OT_BOOLEAN      | false           | Verbose         |\n"
"|                 |                 |                 | evaluation  for |\n"
"|                 |                 |                 | debugging       |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| warn_initial_bo | OT_BOOLEAN      | false           | Warn if the     |\n"
"| unds            |                 |                 | initial guess   |\n"
"|                 |                 |                 | does not        |\n"
"|                 |                 |                 | satisfy LBX and |\n"
"|                 |                 |                 | UBX             |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"| yEinitial       | OT_STRING       | \"simple\"        | Initial         |\n"
"|                 |                 |                 | multiplier.     |\n"
"|                 |                 |                 | Simple (all     |\n"
"|                 |                 |                 | zero) or least  |\n"
"|                 |                 |                 | (LSQ).          |\n"
"+-----------------+-----------------+-----------------+-----------------+\n"
"\n"
"\n"
">List of available monitors\n"
"+-------------+\n"
"|     Id      |\n"
"+=============+\n"
"| dx          |\n"
"+-------------+\n"
"| eval_f      |\n"
"+-------------+\n"
"| eval_g      |\n"
"+-------------+\n"
"| eval_grad_f |\n"
"+-------------+\n"
"| eval_h      |\n"
"+-------------+\n"
"| eval_jac_g  |\n"
"+-------------+\n"
"| inputs      |\n"
"+-------------+\n"
"| outputs     |\n"
"+-------------+\n"
"| qp          |\n"
"+-------------+\n"
"\n"
"\n"
">List of available stats\n"
"+---------------+\n"
"|      Id       |\n"
"+===============+\n"
"| iter_count    |\n"
"+---------------+\n"
"| return_status |\n"
"+---------------+\n"
"\n"
"\n"
"\n"
"\n"
;
