from __future__ import annotations

from typing import Any, Iterator, Mapping, Self, Sequence, Tuple, overload
from ._api_surface import *
from ._api_surface import Callback as _SurfaceCallback
from ._api_surface import CasadiMeta as _SurfaceCasadiMeta
from ._api_surface import DM as _SurfaceDM
from ._api_surface import DaeBuilder as _SurfaceDaeBuilder
from ._api_surface import Function as _SurfaceFunction
from ._api_surface import GlobalOptions as _SurfaceGlobalOptions
from ._api_surface import Importer as _SurfaceImporter
from ._api_surface import Linsol as _SurfaceLinsol
from ._api_surface import MX as _SurfaceMX
from ._api_surface import NlpBuilder as _SurfaceNlpBuilder
from ._api_surface import Opti as _SurfaceOpti
from ._api_surface import OptiSol as _SurfaceOptiSol
from ._api_surface import Sparsity as _SurfaceSparsity
from ._api_surface import SX as _SurfaceSX

__version__: str
__all__: list[str]

inf: float
nan: float
pi: float

OP_CONST: int
OP_INPUT: int
OP_OUTPUT: int
OP_ADD: int
OP_MUL: int
OP_MTIMES: int
OP_TWICE: int


class _CasadiObject:
    ...


class Sparsity(_SurfaceSparsity, _CasadiObject):
    inf: float
    nan: float
    def __init__(self, *args: Any) -> None: ...
    shape: Tuple[int, int]
    T: Sparsity
    @staticmethod
    def dense(nrow: int, ncol: int = ...) -> Sparsity: ...
    @staticmethod
    def diag(n: int) -> Sparsity: ...
    @staticmethod
    def lower(n: int) -> Sparsity: ...
    @staticmethod
    def scalar() -> Sparsity: ...
    @staticmethod
    def triplet(nrow: int, ncol: int, row: Sequence[int], col: Sequence[int]) -> Sparsity: ...
    @staticmethod
    def rand(nrow: int, ncol: int, density: float = ...) -> Sparsity: ...
    def size1(self) -> int: ...
    def size2(self) -> int: ...
    def __add__(self, other: Any) -> Sparsity: ...
    def __radd__(self, other: Any) -> Sparsity: ...


class _CasadiMatrix(_CasadiObject):
    shape: Tuple[int, int]
    T: Self
    def size1(self) -> int: ...
    def size2(self) -> int: ...
    def sparsity(self) -> Sparsity: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __add__(self, other: Any) -> Self: ...
    def __radd__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __rsub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> Self: ...
    def __rmul__(self, other: Any) -> Self: ...
    def __truediv__(self, other: Any) -> Self: ...
    def __rtruediv__(self, other: Any) -> Self: ...
    def __pow__(self, other: Any) -> Self: ...
    def __rpow__(self, other: Any) -> Self: ...
    def __matmul__(self, other: Any) -> Self: ...
    def __rmatmul__(self, other: Any) -> Self: ...
    def __neg__(self) -> Self: ...
    def __lt__(self, other: Any) -> Self: ...
    def __le__(self, other: Any) -> Self: ...
    def __gt__(self, other: Any) -> Self: ...
    def __ge__(self, other: Any) -> Self: ...


class DM(_SurfaceDM, _CasadiMatrix):
    inf: float
    nan: float
    def __init__(self, *args: Any) -> None: ...
    @staticmethod
    def zeros(*args: Any) -> DM: ...
    @staticmethod
    def ones(*args: Any) -> DM: ...
    @staticmethod
    def eye(n: int) -> DM: ...
    @staticmethod
    def rand(*args: Any) -> DM: ...
    def full(self) -> Any: ...
    def sparse(self) -> Any: ...


class SX(_SurfaceSX, _CasadiMatrix):
    def __init__(self, *args: Any) -> None: ...
    @staticmethod
    def sym(name: str, *args: Any) -> SX: ...
    @staticmethod
    def zeros(*args: Any) -> SX: ...
    @staticmethod
    def ones(*args: Any) -> SX: ...
    @staticmethod
    def eye(n: int) -> SX: ...


class MX(_SurfaceMX, _CasadiMatrix):
    def __init__(self, *args: Any) -> None: ...
    @staticmethod
    def sym(name: str, *args: Any) -> MX: ...
    @staticmethod
    def zeros(*args: Any) -> MX: ...
    @staticmethod
    def ones(*args: Any) -> MX: ...
    @staticmethod
    def eye(n: int) -> MX: ...


class Function(_SurfaceFunction, _CasadiObject):
    def __init__(self, *args: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def jacobian(self) -> Function: ...
    def expand(self, *args: Any, **kwargs: Any) -> Function: ...
    def map(self, *args: Any, **kwargs: Any) -> Function: ...
    @overload
    def name_in(self) -> list[str]: ...
    @overload
    def name_in(self, ind: int) -> str: ...
    @overload
    def name_out(self) -> list[str]: ...
    @overload
    def name_out(self, ind: int) -> str: ...
    @overload
    def nnz_in(self) -> int: ...
    @overload
    def nnz_in(self, ind: int) -> int: ...
    @overload
    def nnz_in(self, iname: str) -> int: ...
    @overload
    def nnz_out(self) -> int: ...
    @overload
    def nnz_out(self, ind: int) -> int: ...
    @overload
    def nnz_out(self, oname: str) -> int: ...


class OptiSol(_SurfaceOptiSol, _CasadiObject):
    def value(self, x: Any, values: Sequence[MX] = ...) -> Any: ...


class Opti(_SurfaceOpti, _CasadiObject):
    debug: Any
    f: Any
    g: Any
    x: Any
    lam_g: Any
    def __init__(self, *args: Any) -> None: ...
    def variable(self, *args: Any) -> MX: ...
    def parameter(self, *args: Any) -> MX: ...
    def minimize(self, *args: Any) -> None: ...
    def subject_to(self, *args: Any) -> None: ...
    def solver(
        self,
        solver: str,
        plugin_options: Mapping[str, Any] = ...,
        solver_options: Mapping[str, Any] = ...,
    ) -> None: ...
    def solve(self) -> OptiSol: ...
    def value(self, x: Any, values: Sequence[MX] = ...) -> Any: ...


class Callback(_SurfaceCallback, _CasadiObject):
    def __init__(self, *args: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...


class Importer(_SurfaceImporter, _CasadiObject):
    def __init__(self, *args: Any) -> None: ...
    @staticmethod
    def has_plugin(name: str) -> bool: ...


class NlpBuilder(_SurfaceNlpBuilder, _CasadiObject):
    def __init__(self, *args: Any) -> None: ...


class DaeBuilder(_SurfaceDaeBuilder, _CasadiObject):
    def __init__(self, *args: Any) -> None: ...


class Linsol(_SurfaceLinsol, Function):
    def __init__(self, *args: Any) -> None: ...


class GlobalOptions(_SurfaceGlobalOptions):
    @staticmethod
    def setCasadiPath(path: str) -> None: ...
    @staticmethod
    def setCasadiIncludePath(path: str) -> None: ...
    @staticmethod
    def getCasadiPath() -> str: ...
    @staticmethod
    def getCasadiIncludePath() -> str: ...


class CasadiMeta(_SurfaceCasadiMeta):
    @staticmethod
    def version() -> str: ...
    @staticmethod
    def git_describe() -> str: ...
    @staticmethod
    def swig_flags() -> str: ...
    @staticmethod
    def compiler_flags() -> str: ...


@overload
def sin(x: float) -> float: ...
@overload
def sin(x: DM) -> DM: ...
@overload
def sin(x: SX) -> SX: ...
@overload
def sin(x: MX) -> MX: ...
@overload
def sin(x: Any) -> Any: ...


@overload
def cos(x: float) -> float: ...
@overload
def cos(x: DM) -> DM: ...
@overload
def cos(x: SX) -> SX: ...
@overload
def cos(x: MX) -> MX: ...
@overload
def cos(x: Any) -> Any: ...


@overload
def tan(x: float) -> float: ...
@overload
def tan(x: DM) -> DM: ...
@overload
def tan(x: SX) -> SX: ...
@overload
def tan(x: MX) -> MX: ...
@overload
def tan(x: Any) -> Any: ...


@overload
def exp(x: float) -> float: ...
@overload
def exp(x: DM) -> DM: ...
@overload
def exp(x: SX) -> SX: ...
@overload
def exp(x: MX) -> MX: ...
@overload
def exp(x: Any) -> Any: ...


@overload
def sqrt(x: float) -> float: ...
@overload
def sqrt(x: DM) -> DM: ...
@overload
def sqrt(x: SX) -> SX: ...
@overload
def sqrt(x: MX) -> MX: ...
@overload
def sqrt(x: Any) -> Any: ...


@overload
def sign(x: float) -> float: ...
@overload
def sign(x: DM) -> DM: ...
@overload
def sign(x: SX) -> SX: ...
@overload
def sign(x: MX) -> MX: ...
@overload
def sign(x: Any) -> Any: ...


@overload
def jacobian(ex: DM, arg: DM, opts: Mapping[str, Any] = ...) -> DM: ...
@overload
def jacobian(ex: SX, arg: SX, opts: Mapping[str, Any] = ...) -> SX: ...
@overload
def jacobian(ex: MX, arg: MX, opts: Mapping[str, Any] = ...) -> MX: ...


@overload
def gradient(ex: DM, arg: DM, opts: Mapping[str, Any] = ...) -> DM: ...
@overload
def gradient(ex: SX, arg: SX, opts: Mapping[str, Any] = ...) -> SX: ...
@overload
def gradient(ex: MX, arg: MX, opts: Mapping[str, Any] = ...) -> MX: ...


def hessian(ex: Any, arg: Any, opts: Mapping[str, Any] = ...) -> tuple[Any, Any]: ...


@overload
def dot(x: DM, y: DM) -> DM: ...
@overload
def dot(x: SX, y: SX) -> SX: ...
@overload
def dot(x: MX, y: MX) -> MX: ...
@overload
def dot(x: Any, y: Any) -> Any: ...


@overload
def det(x: DM) -> DM: ...
@overload
def det(x: SX) -> SX: ...
@overload
def det(x: MX) -> MX: ...
@overload
def det(x: Any) -> Any: ...


@overload
def mtimes(args: Sequence[Sparsity]) -> Sparsity: ...
@overload
def mtimes(args: Sequence[DM]) -> DM: ...
@overload
def mtimes(args: Sequence[SX]) -> SX: ...
@overload
def mtimes(args: Sequence[MX]) -> MX: ...
@overload
def mtimes(x: Sparsity, y: Sparsity) -> Sparsity: ...
@overload
def mtimes(x: DM, y: DM) -> DM: ...
@overload
def mtimes(x: SX, y: SX) -> SX: ...
@overload
def mtimes(x: MX, y: MX) -> MX: ...
@overload
def mtimes(*args: Any) -> Any: ...


@overload
def vertcat(*args: DM) -> DM: ...
@overload
def vertcat(*args: SX) -> SX: ...
@overload
def vertcat(*args: MX) -> MX: ...
@overload
def vertcat(*args: Any) -> Any: ...


@overload
def horzcat(*args: DM) -> DM: ...
@overload
def horzcat(*args: SX) -> SX: ...
@overload
def horzcat(*args: MX) -> MX: ...
@overload
def horzcat(*args: Any) -> Any: ...


def veccat(*args: Any) -> Any: ...
def vcat(*args: Any) -> Any: ...
def vertsplit(*args: Any) -> Sequence[Any]: ...
def vec(*args: Any) -> Any: ...
def diagcat(*args: Any) -> Any: ...
def blockcat(*args: Any) -> Any: ...
def repmat(*args: Any) -> Any: ...
def sparsify(*args: Any) -> Any: ...
def tangent(*args: Any) -> Any: ...
def substitute(*args: Any) -> Any: ...
def collocation_points(order: int, scheme: str) -> list[float]: ...
def norm_inf(*args: Any) -> Any: ...
def fmin(*args: Any) -> Any: ...
def fmax(*args: Any) -> Any: ...
def print_operator(*args: Any) -> str: ...
def if_else(*args: Any) -> Any: ...
def logic_not(*args: Any) -> Any: ...
def has_conic(name: str) -> bool: ...


def nlpsol(*args: Any, **kwargs: Any) -> Function: ...
def qpsol(*args: Any, **kwargs: Any) -> Function: ...
def integrator(*args: Any, **kwargs: Any) -> Function: ...
def interpolant(*args: Any, **kwargs: Any) -> Function: ...
def conic(*args: Any, **kwargs: Any) -> Function: ...
def rootfinder(*args: Any, **kwargs: Any) -> Function: ...
def external(*args: Any, **kwargs: Any) -> Function: ...


def dae_reduce_index(*args: Any, **kwargs: Any) -> Any: ...
def dae_map_semi_expl(*args: Any, **kwargs: Any) -> Any: ...
def dae_init_gen(*args: Any, **kwargs: Any) -> Function: ...


@overload
def integrator_in() -> list[str]: ...
@overload
def integrator_in(ind: int) -> str: ...
@overload
def integrator_out() -> list[str]: ...
@overload
def integrator_out(ind: int) -> str: ...
@overload
def event_in() -> list[str]: ...
@overload
def event_in(ind: int) -> str: ...
@overload
def event_out() -> list[str]: ...
@overload
def event_out(ind: int) -> str: ...
@overload
def nlpsol_out() -> list[str]: ...
@overload
def nlpsol_out(ind: int) -> str: ...
def nlpsol_n_out() -> int: ...
