from __future__ import annotations

from typing import Any, List, Mapping, Sequence, Tuple, overload

__version__: str


class Sparsity:
    def __init__(self, *args: Any) -> None: ...
    shape: Tuple[int, int]
    T: Sparsity
    @staticmethod
    def dense(nrow: int, ncol: int = ...) -> Sparsity: ...
    @staticmethod
    def diag(n: int) -> Sparsity: ...
    def size1(self) -> int: ...
    def size2(self) -> int: ...
    def __getattr__(self, name: str) -> Any: ...


class DM:
    def __init__(self, *args: Any) -> None: ...
    shape: Tuple[int, int]
    T: DM
    @staticmethod
    @overload
    def zeros(nrow: int, ncol: int) -> DM: ...
    @staticmethod
    @overload
    def zeros(rc: Tuple[int, int]) -> DM: ...
    @staticmethod
    @overload
    def zeros(sp: Sparsity) -> DM: ...
    @staticmethod
    @overload
    def ones(nrow: int, ncol: int) -> DM: ...
    @staticmethod
    @overload
    def ones(rc: Tuple[int, int]) -> DM: ...
    @staticmethod
    @overload
    def ones(sp: Sparsity) -> DM: ...
    @staticmethod
    def eye(n: int) -> DM: ...
    def size1(self) -> int: ...
    def size2(self) -> int: ...
    def full(self) -> Any: ...
    def sparse(self) -> Any: ...
    def __add__(self, other: Any) -> DM: ...
    def __sub__(self, other: Any) -> DM: ...
    def __mul__(self, other: Any) -> DM: ...
    def __truediv__(self, other: Any) -> DM: ...
    def __neg__(self) -> DM: ...
    def __getattr__(self, name: str) -> Any: ...


class SX:
    def __init__(self, *args: Any) -> None: ...
    shape: Tuple[int, int]
    T: SX
    @staticmethod
    @overload
    def sym(name: str) -> SX: ...
    @staticmethod
    @overload
    def sym(name: str, nrow: int, ncol: int) -> SX: ...
    @staticmethod
    @overload
    def sym(name: str, rc: Tuple[int, int]) -> SX: ...
    @staticmethod
    @overload
    def sym(name: str, sp: Sparsity) -> SX: ...
    @staticmethod
    @overload
    def sym(name: str, sp: Sparsity, p: int) -> List[SX]: ...
    @staticmethod
    @overload
    def sym(name: str, nrow: int, ncol: int, p: int) -> List[SX]: ...
    @staticmethod
    @overload
    def sym(name: str, sp: Sparsity, p: int, r: int) -> List[List[SX]]: ...
    @staticmethod
    @overload
    def sym(name: str, nrow: int, ncol: int, p: int, r: int) -> List[List[SX]]: ...
    @staticmethod
    @overload
    def zeros(nrow: int, ncol: int) -> SX: ...
    @staticmethod
    @overload
    def zeros(rc: Tuple[int, int]) -> SX: ...
    @staticmethod
    @overload
    def zeros(sp: Sparsity) -> SX: ...
    @staticmethod
    @overload
    def ones(nrow: int, ncol: int) -> SX: ...
    @staticmethod
    @overload
    def ones(rc: Tuple[int, int]) -> SX: ...
    @staticmethod
    @overload
    def ones(sp: Sparsity) -> SX: ...
    @staticmethod
    def eye(n: int) -> SX: ...
    def size1(self) -> int: ...
    def size2(self) -> int: ...
    def __add__(self, other: Any) -> SX: ...
    def __sub__(self, other: Any) -> SX: ...
    def __mul__(self, other: Any) -> SX: ...
    def __truediv__(self, other: Any) -> SX: ...
    def __neg__(self) -> SX: ...
    def __getattr__(self, name: str) -> Any: ...


class MX:
    def __init__(self, *args: Any) -> None: ...
    shape: Tuple[int, int]
    T: MX
    @staticmethod
    @overload
    def sym(name: str) -> MX: ...
    @staticmethod
    @overload
    def sym(name: str, nrow: int, ncol: int) -> MX: ...
    @staticmethod
    @overload
    def sym(name: str, rc: Tuple[int, int]) -> MX: ...
    @staticmethod
    @overload
    def sym(name: str, sp: Sparsity) -> MX: ...
    @staticmethod
    @overload
    def sym(name: str, sp: Sparsity, p: int) -> List[MX]: ...
    @staticmethod
    @overload
    def sym(name: str, nrow: int, ncol: int, p: int) -> List[MX]: ...
    @staticmethod
    @overload
    def sym(name: str, sp: Sparsity, p: int, r: int) -> List[List[MX]]: ...
    @staticmethod
    @overload
    def sym(name: str, nrow: int, ncol: int, p: int, r: int) -> List[List[MX]]: ...
    @staticmethod
    @overload
    def zeros(nrow: int, ncol: int) -> MX: ...
    @staticmethod
    @overload
    def zeros(rc: Tuple[int, int]) -> MX: ...
    @staticmethod
    @overload
    def zeros(sp: Sparsity) -> MX: ...
    @staticmethod
    @overload
    def ones(nrow: int, ncol: int) -> MX: ...
    @staticmethod
    @overload
    def ones(rc: Tuple[int, int]) -> MX: ...
    @staticmethod
    @overload
    def ones(sp: Sparsity) -> MX: ...
    @staticmethod
    def eye(n: int) -> MX: ...
    def size1(self) -> int: ...
    def size2(self) -> int: ...
    def __add__(self, other: Any) -> MX: ...
    def __sub__(self, other: Any) -> MX: ...
    def __mul__(self, other: Any) -> MX: ...
    def __truediv__(self, other: Any) -> MX: ...
    def __neg__(self) -> MX: ...
    def __getattr__(self, name: str) -> Any: ...


class Function:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, fname: str) -> None: ...
    @overload
    def __init__(self, other: Function) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        ex_in: Sequence[SX],
        ex_out: Sequence[SX],
        opts: Mapping[str, Any] = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        ex_in: Sequence[MX],
        ex_out: Sequence[MX],
        opts: Mapping[str, Any] = ...,
    ) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def jacobian(self) -> Function: ...
    @overload
    def expand(self) -> Function: ...
    @overload
    def expand(self, name: str, opts: Mapping[str, Any]) -> Function: ...
    def map(self, *args: Any, **kwargs: Any) -> Function: ...
    @overload
    def name_in(self) -> List[str]: ...
    @overload
    def name_in(self, ind: int) -> str: ...
    @overload
    def name_out(self) -> List[str]: ...
    @overload
    def name_out(self, ind: int) -> str: ...
    @overload
    def nnz_in(self) -> int: ...
    @overload
    def nnz_in(self, ind: int) -> int: ...
    @overload
    def nnz_in(self, iname: str) -> int: ...
    @overload
    def nnz_out(self) -> int: ...
    @overload
    def nnz_out(self, ind: int) -> int: ...
    @overload
    def nnz_out(self, oname: str) -> int: ...
    def __getattr__(self, name: str) -> Any: ...


class Opti:
    debug: Any
    def __init__(self, *args: Any) -> None: ...
    def variable(self, *args: Any) -> MX: ...
    def parameter(self, *args: Any) -> MX: ...
    def minimize(self, *args: Any) -> None: ...
    def subject_to(self, *args: Any) -> None: ...
    def solver(
        self,
        solver: str,
        plugin_options: Mapping[str, Any] = ...,
        solver_options: Mapping[str, Any] = ...,
    ) -> None: ...
    def solve(self) -> OptiSol: ...
    def value(self, x: Any, values: Sequence[MX] = ...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...


class OptiSol:
    def value(self, x: Any, values: Sequence[MX] = ...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...


class Callback:
    def __init__(self, *args: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class Importer:
    def __init__(self, *args: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class NlpBuilder:
    def __init__(self, *args: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


@overload
def sin(x: float) -> float: ...
@overload
def sin(x: DM) -> DM: ...
@overload
def sin(x: SX) -> SX: ...
@overload
def sin(x: MX) -> MX: ...


@overload
def jacobian(ex: DM, arg: DM, opts: Mapping[str, Any] = ...) -> DM: ...
@overload
def jacobian(ex: SX, arg: SX, opts: Mapping[str, Any] = ...) -> SX: ...
@overload
def jacobian(ex: MX, arg: MX, opts: Mapping[str, Any] = ...) -> MX: ...


@overload
def gradient(ex: DM, arg: DM, opts: Mapping[str, Any] = ...) -> DM: ...
@overload
def gradient(ex: SX, arg: SX, opts: Mapping[str, Any] = ...) -> SX: ...
@overload
def gradient(ex: MX, arg: MX, opts: Mapping[str, Any] = ...) -> MX: ...


@overload
def dot(x: DM, y: DM) -> DM: ...
@overload
def dot(x: SX, y: SX) -> SX: ...
@overload
def dot(x: MX, y: MX) -> MX: ...


@overload
def mtimes(args: Sequence[Sparsity]) -> Sparsity: ...
@overload
def mtimes(args: Sequence[DM]) -> DM: ...
@overload
def mtimes(args: Sequence[SX]) -> SX: ...
@overload
def mtimes(args: Sequence[MX]) -> MX: ...
@overload
def mtimes(x: Sparsity, y: Sparsity) -> Sparsity: ...
@overload
def mtimes(x: DM, y: DM) -> DM: ...
@overload
def mtimes(x: SX, y: SX) -> SX: ...
@overload
def mtimes(x: MX, y: MX) -> MX: ...


@overload
def vertcat(*args: DM) -> DM: ...
@overload
def vertcat(*args: SX) -> SX: ...
@overload
def vertcat(*args: MX) -> MX: ...


@overload
def horzcat(*args: DM) -> DM: ...
@overload
def horzcat(*args: SX) -> SX: ...
@overload
def horzcat(*args: MX) -> MX: ...


def nlpsol(*args: Any, **kwargs: Any) -> Function: ...
def qpsol(*args: Any, **kwargs: Any) -> Function: ...
def integrator(*args: Any, **kwargs: Any) -> Function: ...
def interpolant(*args: Any, **kwargs: Any) -> Function: ...
def conic(*args: Any, **kwargs: Any) -> Function: ...


def __getattr__(name: str) -> Any: ...
