[options]
alpaqa/*:with_python=True
alpaqa/*:with_ipopt=False
alpaqa/*:with_external_casadi=True
alpaqa/*:with_qpalm=False
alpaqa/*:with_cutest=True
alpaqa/*:with_json=False
alpaqa/*:with_lbfgsb=False

[settings]
casadi/*:build_type=Release

# QPALM is disabled because of an MSVC ICE:
# 
#   FAILED: [code=3221225477] src/CMakeFiles/qpalm-adapter.dir/Release/interop/qpalm/src/qpalm-adapter.cpp.obj 
#   sccache C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1444~1.352\bin\Hostx64\x64\cl.exe  /nologo /TP -DALPAQA_WITH_LONG_DOUBLE -DALPAQA_WITH_QPALM -DEIGEN_DONT_PARALLELIZE -DLADEL_64BIT_INDICES -DLADEL_SIMPLE_COL_COUNTS -DLADEL_USE_AMD -DQPALM_NONCONVEX -DQPALM_PRINTING -DQPALM_TIMING -DQPALM_USE_LADEL -DQPALM_VERSION_MAJOR=1 -DQPALM_VERSION_MINOR=2 -DQPALM_VERSION_PATCH=6 -DQPALM_VERSION_STR=\"1.2.6\" -DCMAKE_INTDIR=\"Release\" -ID:\a\alpaqa\alpaqa\.py-build-cmake_cache\build\cp311-cp311-win_amd64\include -ID:\a\alpaqa\alpaqa\src\interop\qpalm\include -ID:\a\alpaqa\alpaqa\.py-build-cmake_cache\build\cp311-cp311-win_amd64\src\export -ID:\a\alpaqa\alpaqa\src\alpaqa\include -external:ID:\a\alpaqa\alpaqa\.conan2\p\b\qpalm36c9375940a7b\p\include -external:ID:\a\alpaqa\alpaqa\.conan2\p\b\ladel5a0bd9f10f8cf\p\include -external:ID:\a\alpaqa\alpaqa\.conan2\p\b\eigen557b009256fbf\p\include\eigen3 -external:ID:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -std:c++latest -MD /bigobj /experimental:c11atomics /utf-8 /W3 /wd4127 /wd4458 /wd4251 /wd4305 /wd4661 /wd5030 /showIncludes /Fosrc\CMakeFiles\qpalm-adapter.dir\Release\interop\qpalm\src\qpalm-adapter.cpp.obj /Fdsrc\CMakeFiles\qpalm-adapter.dir\Release\qpalm-adapter.pdb /FS -c D:\a\alpaqa\alpaqa\src\interop\qpalm\src\qpalm-adapter.cpp
#   D:\a\alpaqa\alpaqa\src\interop\qpalm\src\qpalm-adapter.cpp(115): fatal error C1001: Internal compiler error.
#   (compiler file 'msc1.cpp', line 1589)
#    To work around this problem, try simplifying or changing the program near the locations listed above.
#   If possible please provide a repro here: https://developercommunity.visualstudio.com 
#   Please choose the Technical Support command on the Visual C++ 
#    Help menu, or open the Technical Support help file for more information
#   D:\a\alpaqa\alpaqa\src\interop\qpalm\src\qpalm-adapter.cpp(115): note: the template instantiation context (the oldest one first) is
#   D:\a\alpaqa\alpaqa\src\interop\qpalm\src\qpalm-adapter.cpp(49): note: see reference to class template instantiation 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Sparsity,alpaqa::build_qpalm_problem::SparseCSC>' being compiled
#   D:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include\guanaqo/linalg/sparsity-conversions.hpp(756): note: see reference to class template instantiation 'std::variant<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\variant(931): note: see reference to alias template instantiation 'std::_SMF_control<std::_Variant_destroy_layer_<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xsmf_control.h(159): note: see reference to alias template instantiation 'std::_SMF_control_move_assign<std::_Variant_destroy_layer_<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xsmf_control.h(154): note: see reference to alias template instantiation 'std::_SMF_control_copy_assign<std::_Variant_destroy_layer_<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xsmf_control.h(117): note: see reference to alias template instantiation 'std::_SMF_control_move<std::_Variant_destroy_layer_<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xsmf_control.h(80): note: see reference to alias template instantiation 'std::_SMF_control_copy<std::_Variant_destroy_layer_<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,To>,guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xsmf_control.h(49): note: see reference to variable template 'const bool conjunction_v<std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Dense,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,int>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,long>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<int,__int64>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,long>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<long,__int64>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCSC<__int64,__int64>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<int>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<long>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > >,std::is_copy_constructible<guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> > > >' being compiled
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\xsmf_control.h(49): note: see reference to class template instantiation 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>' being compiled
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   D:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include\guanaqo/linalg/sparsity-conversions.hpp(422): note: while compiling class template member function 'guanaqo::linalg::sparsity::SparseCSC<__int64,__int64> guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>::convert_sparsity(guanaqo::linalg::sparsity::SparseCOO<__int64>,guanaqo::linalg::sparsity::SparsityConversionRequest<To>)'
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   D:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include\guanaqo/linalg/sparsity-conversions.hpp(503): note: see the first reference to 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>::convert_sparsity' in 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>::SparsityConverter'
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   D:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include\guanaqo/linalg/sparsity-conversions.hpp(826): note: see the first reference to 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::SparseCOO<__int64>,To>::SparsityConverter' in 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Sparsity,alpaqa::build_qpalm_problem::SparseCSC>::wrap_converter::<lambda_1>::operator ()'
#           with
#           [
#               To=alpaqa::build_qpalm_problem::SparseCSC
#           ]
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\type_traits(1680): note: see the first reference to 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Sparsity,alpaqa::build_qpalm_problem::SparseCSC>::wrap_converter::<lambda_1>::operator ()' in 'std::invoke'
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\variant(1430): note: see the first reference to 'std::invoke' in 'std::_Variant_dispatcher<std::_Visit_strategy<2>::_Visit2::_Indices>::_Dispatch2'
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\variant(1509): note: see the first reference to 'std::_Variant_dispatcher<std::_Visit_strategy<2>::_Visit2::_Indices>::_Dispatch2' in 'std::_Visit_strategy<2>::_Visit2'
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\variant(1554): note: see the first reference to 'std::_Visit_strategy<2>::_Visit2' in 'std::_Visit_impl'
#   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\include\variant(1599): note: see the first reference to 'std::_Visit_impl' in 'std::visit'
#   D:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include\guanaqo/linalg/sparsity-conversions.hpp(755): note: see the first reference to 'std::visit' in 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Sparsity,alpaqa::build_qpalm_problem::SparseCSC>::SparsityConverter'
#   D:\a\alpaqa\alpaqa\src\interop\qpalm\src\qpalm-adapter.cpp(49): note: see the first reference to 'guanaqo::linalg::sparsity::SparsityConverter<guanaqo::linalg::sparsity::Sparsity,alpaqa::build_qpalm_problem::SparseCSC>::SparsityConverter' in 'alpaqa::build_qpalm_problem'
#   D:\a\alpaqa\alpaqa\.conan2\p\b\guanaa6dd4439926d8\p\include\guanaqo/linalg/sparsity-conversions.hpp(448): note: see reference to function template instantiation 'void guanaqo::linalg::sort_triplets<std::vector<Index,std::allocator<Index>>&,std::vector<Index,std::allocator<Index>>&,std::vector<Index,std::allocator<Index>>&>(std::vector<Index,std::allocator<Index>> &,std::vector<Index,std::allocator<Index>> &,std::vector<Index,std::allocator<Index>> &)' being compiled
#           with
#           [
#               Index=__int64
#           ]
#   INTERNAL COMPILER ERROR in 'C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1444~1.352\bin\Hostx64\x64\cl.exe'
#       Please choose the Technical Support command on the Visual C++
#       Help menu, or open the Technical Support help file for more information
#   [29/53] Building CXX object src\CMakeFiles\alpaqa.dir\Release\alpaqa\src\inner\directions\panoc\structured-newton.cpp.obj
#   [30/53] Building CXX object src\CMakeFiles\alpaqa.dir\Release\alpaqa\src\inner\directions\panoc\convex-newton.cpp.obj
#   [31/53] Building CXX object src\CMakeFiles\dl-loader.dir\Release\interop\dl\src\dl-problem.cpp.obj
#   ninja: build stopped: subcommand failed.
#   Access violation
