FIND_PATH(SDPA_INCLUDE_DIR
sdpa_call.h
~/local/sdpa.7.3.1/include/
~/local/include/
/usr/local/include/
/usr/local/sdpa.7.3.1/include/
)

FIND_PATH(MUMPS_INCLUDE_DIR
dmumps_root.h
${SDPA_INCLUDE_DIR}/../mumps/build/include/
~/local/include/
/usr/local/include/)

IF (SDPA_INCLUDE_DIR AND MUMPS_INCLUDE_DIR)
  SET(FOUND_SDPA_INCLUDES TRUE)
  SET(SDPA_INCLUDE_DIRS ${SDPA_INCLUDE_DIR} ${MUMPS_INCLUDE_DIR})
  MESSAGE(STATUS "Found SDPA include dirs: ${SDPA_INCLUDE_DIRS}")
  MESSAGE(STATUS "Found MUMPS include dirs: ${MUMPS_INCLUDE_DIR}")
ELSE (SDPA_INCLUDE_DIR AND MUMPS_INCLUDE_DIR)
  MESSAGE(STATUS "Could not find SDPA include dirs")
ENDIF (SDPA_INCLUDE_DIR AND MUMPS_INCLUDE_DIR)

FIND_LIBRARY(SDPA_LIBRARY
NAMES sdpa
PATHS ${SDPA_LIB_DIR} ${SDPA_INCLUDE_DIR}/../lib ~/local/lib /usr/local/lib)

FIND_LIBRARY(MUMPS_LIBRARY
NAMES dmumps
PATHS ${MUMPS_INCLUDE_DIR}/../lib ~/local/lib /usr/local/lib)

FIND_LIBRARY(MUMPS_COMMON_LIBRARY
NAMES mumps_common
PATHS ${MUMPS_INCLUDE_DIR}/../lib ~/local/lib /usr/local/lib)

FIND_LIBRARY(MUMPS_PORD_LIBRARY
NAMES pord
PATHS ${MUMPS_INCLUDE_DIR}/../lib ~/local/lib /usr/local/lib)

FIND_LIBRARY(MUMPS_MPISEQ_LIBRARY
NAMES mpiseq
PATHS ${MUMPS_INCLUDE_DIR}/../libseq ~/local/lib /usr/local/lib)

IF(SDPA_LIBRARY AND MUMPS_LIBRARY AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY AND MUMPS_MPISEQ_LIBRARY)
  SET(FOUND_SDPA_LIBS TRUE)
  SET(SDPA_LIBRARIES ${SDPA_LIBRARY} ${MUMPS_LIBRARY} ${MUMPS_COMMON_LIBRARY} ${MUMPS_PORD_LIBRARY} ${MUMPS_MPISEQ_LIBRARY} lapack pthread)
  MESSAGE(STATUS "Found SDPA libs: ${SDPA_LIBRARIES}")
ELSE(SDPA_LIBRARY AND MUMPS_LIBRARY AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY AND MUMPS_MPISEQ_LIBRARY)
  MESSAGE(STATUS "Could not find SDPA libs")
ENDIF(SDPA_LIBRARY AND MUMPS_LIBRARY AND MUMPS_COMMON_LIBRARY AND MUMPS_PORD_LIBRARY AND MUMPS_MPISEQ_LIBRARY)

IF(FOUND_SDPA_INCLUDES AND FOUND_SDPA_LIBS)
  SET(FOUND_SDPA TRUE)
ENDIF(FOUND_SDPA_INCLUDES AND FOUND_SDPA_LIBS)
