# TRY TO FIND THE METIS LIBRARY

FIND_LIBRARY(METIS_LIB
    names coinmetis metis
    HINTS $ENV{METIS})

IF(METIS_LIB)
  MESSAGE(STATUS "Found METIS: ${METIS_LIB}")
  SET(METIS_LIBRARIES ${METIS_LIB})
  SET(METIS_FOUND TRUE)
ELSE(METIS_LIB)
  SET(METIS_FOUND FALSE)
  MESSAGE(STATUS "Could not find METIS; looking in environmental variable METIS ($ENV{METIS})")
ENDIF(METIS_LIB)
