message(STATUS "Looking for clang 3.4.2")

find_path(CLANG_DEP_${D} ${D} $ENV{CLANG}/lib)
set(CLANG_INCLUDE_DIR $ENV{CLANG}/include)

# version
#set(CLANG_DEP LLVMCore LLVMExecutionEngine LLVMMC LLVMMCJIT LLVMSupport LLVMX86CodeGen LLVMX86AsmPrinter LLVMX86AsmParser LLVMX86Desc LLVMX86Info LLVMX86Disassembler clangBasic clangCodeGen clangDriver clangFrontend LLVMExecutionEngine LLVMRuntimeDyld LLVMX86CodeGen LLVMAsmPrinter LLVMSelectionDAG LLVMCodeGen LLVMX86Desc LLVMX86AsmPrinter LLVMX86Utils LLVMX86Info LLVMMCDisassembler clangDriver LLVMOption clangParse clangSerialization clangSema clangEdit clangAnalysis LLVMTarget clangAST clangLex clangBasic LLVMBitWriter LLVMipo LLVMVectorize LLVMIRReader LLVMAsmParser LLVMInstrumentation LLVMLinker LLVMObjCARCOpts LLVMScalarOpts LLVMInstCombine LLVMObject LLVMMCParser LLVMMC LLVMBitReader LLVMTransformUtils LLVMipa LLVMAnalysis LLVMCore LLVMSupport rt dl tinfo pthread z m)

# version 3.4.2
#set(CLANG_DEP LLVMJIT LLVMInterpreter LLVMX86CodeGen LLVMBitWriter LLVMIRReader LLVMipo LLVMLinker LLVMRuntimeDyld LLVMExecutionEngine LLVMAsmPrinter LLVMSelectionDAG LLVMX86Desc LLVMAsmParser LLVMBitReader LLVMVectorize LLVMMCParser LLVMCodeGen LLVMX86AsmPrinter LLVMX86Info LLVMObjCARCOpts LLVMScalarOpts LLVMX86Utils LLVMInstCombine LLVMTransformUtils LLVMipa LLVMAnalysis LLVMTarget LLVMCore LLVMMC LLVMObject LLVMSupport rt dl tinfo pthread z clangFrontend clangSerialization clangDriver clangCodeGen clangSema clangStaticAnalyzerFrontend clangStaticAnalyzerCheckers clangStaticAnalyzerCore clangAnalysis clangRewriteCore clangRewriteFrontend clangAST clangParse clangLex clangBasic LLVMBitWriter LLVMIRReader LLVMipo LLVMLinker LLVMVectorize LLVMInstrumentation clangFrontend clangSerialization LLVMBitReader clangDriver LLVMOption clangRewriteCore clangParse clangSema LLVMX86CodeGen LLVMAsmParser clangAnalysis clangEdit LLVMAArch64AsmParser LLVMAArch64Disassembler LLVMARMCodeGen LLVMARMAsmParser LLVMARMDisassembler LLVMCppBackendCodeGen LLVMHexagonCodeGen LLVMMipsCodeGen LLVMMipsAsmParser LLVMMipsDisassembler LLVMMSP430CodeGen LLVMNVPTXCodeGen LLVMPowerPCCodeGen LLVMPowerPCAsmParser LLVMR600CodeGen LLVMSparcCodeGen LLVMSystemZCodeGen LLVMSystemZAsmParser LLVMSystemZDisassembler LLVMX86AsmParser LLVMX86Disassembler LLVMX86Desc LLVMX86AsmPrinter LLVMX86Utils LLVMX86Info LLVMXCoreCodeGen LLVMXCoreDisassembler LLVMAArch64CodeGen LLVMAsmPrinter LLVMMCParser LLVMSelectionDAG LLVMCodeGen LLVMObjCARCOpts LLVMScalarOpts LLVMInstCombine LLVMTransformUtils LLVMipa LLVMAnalysis LLVMARMDesc LLVMCppBackendInfo LLVMHexagonAsmPrinter LLVMMipsDesc LLVMMSP430Desc LLVMNVPTXDesc LLVMPowerPCDesc LLVMR600Desc LLVMSparcDesc LLVMSystemZDesc LLVMXCoreDesc LLVMAArch64Desc LLVMARMAsmPrinter LLVMARMInfo LLVMHexagonDesc LLVMMipsAsmPrinter LLVMMipsInfo LLVMMSP430AsmPrinter LLVMMSP430Info LLVMNVPTXAsmPrinter LLVMNVPTXInfo LLVMPowerPCAsmPrinter LLVMPowerPCInfo LLVMR600AsmPrinter LLVMR600Info LLVMSparcInfo LLVMSystemZAsmPrinter LLVMSystemZInfo LLVMXCoreAsmPrinter LLVMXCoreInfo LLVMAArch64AsmPrinter LLVMAArch64Info LLVMTarget LLVMHexagonInfo LLVMAArch64Utils LLVMCore clangAST clangLex clangBasic LLVMMC LLVMObject LLVMSupport rt dl tinfo pthread z m)
set(CLANG_DEP LLVMJIT LLVMInterpreter LLVMX86CodeGen LLVMBitWriter LLVMIRReader LLVMipo LLVMLinker LLVMRuntimeDyld LLVMExecutionEngine LLVMAsmPrinter LLVMSelectionDAG LLVMX86Desc LLVMAsmParser LLVMBitReader LLVMVectorize LLVMMCParser LLVMCodeGen LLVMX86AsmPrinter LLVMX86Info LLVMObjCARCOpts LLVMScalarOpts LLVMX86Utils LLVMInstCombine LLVMTransformUtils LLVMipa LLVMAnalysis LLVMTarget LLVMCore LLVMMC LLVMObject LLVMSupport clangFrontend clangSerialization clangDriver clangCodeGen clangSema clangAnalysis clangRewriteCore clangRewriteFrontend clangAST clangParse clangLex clangBasic LLVMBitWriter LLVMIRReader LLVMipo LLVMLinker LLVMVectorize LLVMInstrumentation clangFrontend clangSerialization LLVMBitReader clangDriver LLVMOption clangRewriteCore clangParse clangSema LLVMX86CodeGen LLVMAsmParser clangAnalysis clangEdit LLVMAArch64AsmParser LLVMAArch64Disassembler LLVMARMCodeGen LLVMARMAsmParser LLVMARMDisassembler LLVMCppBackendCodeGen LLVMHexagonCodeGen LLVMMipsCodeGen LLVMMipsAsmParser LLVMMipsDisassembler LLVMMSP430CodeGen LLVMNVPTXCodeGen LLVMPowerPCCodeGen LLVMPowerPCAsmParser LLVMR600CodeGen LLVMSparcCodeGen LLVMSystemZCodeGen LLVMSystemZAsmParser LLVMSystemZDisassembler LLVMX86AsmParser LLVMX86Disassembler LLVMX86Desc LLVMX86AsmPrinter LLVMX86Utils LLVMX86Info LLVMXCoreCodeGen LLVMXCoreDisassembler LLVMAArch64CodeGen LLVMAsmPrinter LLVMMCParser LLVMSelectionDAG LLVMCodeGen LLVMObjCARCOpts LLVMScalarOpts LLVMInstCombine LLVMTransformUtils LLVMipa LLVMAnalysis LLVMARMDesc LLVMCppBackendInfo LLVMHexagonAsmPrinter LLVMMipsDesc LLVMMSP430Desc LLVMNVPTXDesc LLVMPowerPCDesc LLVMR600Desc LLVMSparcDesc LLVMSystemZDesc LLVMXCoreDesc LLVMAArch64Desc LLVMARMAsmPrinter LLVMARMInfo LLVMHexagonDesc LLVMMipsAsmPrinter LLVMMipsInfo LLVMMSP430AsmPrinter LLVMMSP430Info LLVMNVPTXAsmPrinter LLVMNVPTXInfo LLVMPowerPCAsmPrinter LLVMPowerPCInfo LLVMR600AsmPrinter LLVMR600Info LLVMSparcInfo LLVMSystemZAsmPrinter LLVMSystemZInfo LLVMXCoreAsmPrinter LLVMXCoreInfo LLVMAArch64AsmPrinter LLVMAArch64Info LLVMTarget LLVMHexagonInfo LLVMAArch64Utils LLVMCore clangAST clangLex clangBasic LLVMMC LLVMObject LLVMSupport)


set(CLANG_LIBRARIES "")
foreach(D ${CLANG_DEP})
  find_library(CLANG_DEP_${D} ${D} $ENV{CLANG}/lib)
  set(CLANG_LIBRARIES "${CLANG_LIBRARIES}" ${CLANG_DEP_${D}})
endforeach()

if(MINGW)
  message("/usr/${PREFIX}/lib")
  find_library(CLANG_EXTRA_LIBS imagehlp /usr/${PREFIX}/lib)
  set(CLANG_LIBRARIES "${CLANG_LIBRARIES}" ${CLANG_EXTRA_LIBS})
  message("${CLANG_LIBRARIES}")
endif()


set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DCLANG_ENABLE_OBJC_REWRITER -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fPIC -fvisibility-inlines-hidden -ffunction-sections -fdata-sections -fno-common -fno-strict-aliasing")

set(CLANG_FOUND TRUE)

