FIND_PATH(LIFTOPT_INCLUDE_DIR 
liftopt.hpp
HINTS $ENV{LIFTOPT}/include
)

FIND_PATH(LIFTOPT_SRC_INCLUDE_DIR 
liftopt.hpp
HINTS $ENV{LIFTOPT_SRC}/INCLUDE
)

FIND_PATH(SONIC_INCLUDE_DIR 
sonic++.h
HINTS $ENV{SONIC}/include
)

FIND_PATH(COMMON_CODE_INCLUDE_DIR 
CommonCodeUtilitiesForwardDeclarations.hpp
HINTS $ENV{COMMON_CODE}/include
)

IF (LIFTOPT_INCLUDE_DIR AND SONIC_INCLUDE_DIR AND COMMON_CODE_INCLUDE_DIR AND LIFTOPT_SRC_INCLUDE_DIR )
   SET(LIFTOPT_FOUND_INCLUDE TRUE)
   SET(LIFTOPT_INCLUDE_DIRS ${LIFTOPT_INCLUDE_DIR} ${SONIC_INCLUDE_DIR} ${COMMON_CODE_INCLUDE_DIR} ${LIFTOPT_SRC_INCLUDE_DIR} )
   MESSAGE(STATUS "Found LIFTOPT include dirs: ${LIFTOPT_INCLUDE_DIRS}")
ELSE (LIFTOPT_INCLUDE_DIR AND SONIC_INCLUDE_DIR AND COMMON_CODE_INCLUDE_DIR AND LIFTOPT_SRC_INCLUDE_DIR )
   MESSAGE(STATUS "Could not find LIFTOPT include dir")
ENDIF (LIFTOPT_INCLUDE_DIR AND SONIC_INCLUDE_DIR AND COMMON_CODE_INCLUDE_DIR AND LIFTOPT_SRC_INCLUDE_DIR )

FIND_LIBRARY(LIFTOPT_LIBRARY
NAMES liftopt HINTS $ENV{LIFTOPT}/lib $ENV{LIFTOPT}/lib64)

FIND_LIBRARY(SONIC_LIBRARY
NAMES sonic HINTS $ENV{SONIC}/lib $ENV{SONIC}/lib64)

FIND_LIBRARY(COMMON_CODE_LOGGING NAMES common_code_logging HINTS $ENV{COMMON_CODE}/lib $ENV{COMMON_CODE}/lib64)
FIND_LIBRARY(COMMON_CODE_PROBLEM_HANDLING NAMES common_code_problem_handling HINTS $ENV{COMMON_CODE}/lib $ENV{COMMON_CODE}/lib64)
FIND_LIBRARY(COMMON_CODE_TYPE_CONVERSIONS NAMES common_code_type_conversion HINTS $ENV{COMMON_CODE}/lib $ENV{COMMON_CODE}/lib64)
FIND_LIBRARY(COMMON_CODE_UTILITIES NAMES common_code_utilities HINTS $ENV{COMMON_CODE}/lib $ENV{COMMON_CODE}/lib64)

IF (LIFTOPT_LIBRARY AND SONIC_LIBRARY AND COMMON_CODE_LOGGING AND COMMON_CODE_PROBLEM_HANDLING AND COMMON_CODE_TYPE_CONVERSIONS AND COMMON_CODE_UTILITIES)
   SET(LIFTOPT_FOUND_LIBS TRUE)
   SET(LIFTOPT_LIBRARIES ${LIFTOPT_LIBRARY} ${SONIC_LIBRARY} ${COMMON_CODE_LOGGING} ${COMMON_CODE_PROBLEM_HANDLING} ${COMMON_CODE_TYPE_CONVERSIONS} ${COMMON_CODE_UTILITIES} )
   MESSAGE(STATUS "Found LIFTOPT libs: ${LIFTOPT_LIBRARIES}")
ELSE (LIFTOPT_LIBRARY AND SONIC_LIBRARY AND COMMON_CODE_LOGGING AND COMMON_CODE_PROBLEM_HANDLING AND COMMON_CODE_TYPE_CONVERSIONS AND COMMON_CODE_UTILITIES)
   MESSAGE(STATUS "Could not find sundials libs")
ENDIF (LIFTOPT_LIBRARY AND SONIC_LIBRARY AND COMMON_CODE_LOGGING AND COMMON_CODE_PROBLEM_HANDLING AND COMMON_CODE_TYPE_CONVERSIONS AND COMMON_CODE_UTILITIES)

IF(LIFTOPT_FOUND_INCLUDE AND LIFTOPT_FOUND_LIBS)
  SET(LIFTOPT_FOUND TRUE)
ENDIF(LIFTOPT_FOUND_INCLUDE AND LIFTOPT_FOUND_LIBS)
