name: 'CI Tests: C++'

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  release:
    types: ['released', 'prereleased']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { host: x86_64-bionic-linux-gnu, tests: ExperimentalTest }
          - { host: aarch64-rpi3-linux-gnu, tests: '' }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Conan
        uses: ./.github/workflows/setup-conan
        with:
          python-version: '3.12'
          cache-key: build-linux

      - name: Install CasADi
        run: python3 -m pip install casadi~=3.7.1

      - name: Build and package
        run: ./scripts/ci/package-linux.sh ${{ matrix.host }} "${{ matrix.tests }}"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: alpaqa-${{ matrix.host }}
          retention-days: 1
          path: |
            build/pkg/alpaqa*.tar.gz
            build/pkg/*alpaqa*.deb

      - run: conan cache clean

  test:
    needs: [build]
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    strategy:
      matrix:
        config: [Release, Debug]
        host: [x86_64-bionic-linux-gnu]
    env:
      CFLAGS: '-march=haswell' # important for ABI compatibility (Eigen)
      CXXFLAGS: '-march=haswell' 
    steps:
      # Git clone
      - name: Install git
        run: >
          apt -y update && apt -y install --no-install-recommends
          git wget ca-certificates g++ gfortran ninja-build pkg-config
          python3-pip libeigen3-dev libgtest-dev libgmock-dev
      - uses: actions/checkout@v4
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: alpaqa-${{ matrix.host }}
          path: package
      - name: Install
        run: apt install -y ./package/*alpaqa*.deb
      - name: Install CMake
        run: |
          version="4.1.1"
          wget -N https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version-Linux-x86_64.sh
          bash cmake-$version-Linux-x86_64.sh --skip-license --prefix="/usr/local"
      - name: Install guanaqo
        run: |
          git clone https://github.com/tttapa/guanaqo --branch=1.0.0-alpha.16
          cmake -B build-guanaqo -S guanaqo -G "Ninja Multi-Config" -DBUILD_TESTING=Off
          cmake --build build-guanaqo --config ${{ matrix.config }}
          cmake --install build-guanaqo --config ${{ matrix.config }} --prefix=/usr/local
      - name: Build examples (${{ matrix.config }})
        run: |
          cmake -B build-examples -S examples -G "Ninja Multi-Config"
          cmake --build build-examples -j --config ${{ matrix.config }}
      - name: Build tests (${{ matrix.config }})
        run: |
          cmake -B build-tests -S test -G "Ninja Multi-Config"
          cmake --build build-tests -j --config ${{ matrix.config }}
      - name: Upload (${{ matrix.config }})
        uses: actions/upload-artifact@v4
        with:
          name: alpaqa-${{ matrix.host }}-test-examples-${{ matrix.config }}
          retention-days: 1
          path: |
            build-examples/C++/CustomCppProblem/${{ matrix.config }}/custom-cpp-problem-example
            build-examples/C++/SimpleUnconstrProblem/${{ matrix.config }}/simple-unconstr-cpp-problem-example
            build-examples/C++/FortranProblem/${{ matrix.config }}/fortran-problem-example
            build-examples/C++/DLProblem/${{ matrix.config }}/dl-problem-example
            build-examples/C++/DLProblem/${{ matrix.config }}/test-matmul
            build-tests/${{ matrix.config }}/tests
            build-tests/${{ matrix.config }}/librosenbrock_functions_test.so
      - name: Run examples (${{ matrix.config }})
        run: |
          set -ex
          ./build-examples/C++/CustomCppProblem/${{ matrix.config }}/custom-cpp-problem-example
          ./build-examples/C++/SimpleUnconstrProblem/${{ matrix.config }}/simple-unconstr-cpp-problem-example
          ./build-examples/C++/FortranProblem/${{ matrix.config }}/fortran-problem-example
          ./build-examples/C++/DLProblem/${{ matrix.config }}/dl-problem-example
          ./build-examples/C++/DLProblem/${{ matrix.config }}/test-matmul
      - name: Run tests (${{ matrix.config }})
        run: |
          set -ex
          ./build-tests/${{ matrix.config }}/tests
          cmake --build build-tests -t test --config ${{ matrix.config }}
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
      - name: Install Valgrind
        run: |
          apt update
          apt install -y valgrind --no-install-recommends
      - name: Run examples (Valgrind, ${{ matrix.config }})
        run: |
          set -ex
          valgrind --gen-suppressions=all --suppressions=scripts/valgrind/cpp.supp --error-exitcode=234 ./build-examples/C++/CustomCppProblem/${{ matrix.config }}/custom-cpp-problem-example
          valgrind --gen-suppressions=all --suppressions=scripts/valgrind/cpp.supp --error-exitcode=234 ./build-examples/C++/SimpleUnconstrProblem/${{ matrix.config }}/simple-unconstr-cpp-problem-example
          valgrind --gen-suppressions=all --suppressions=scripts/valgrind/cpp.supp --error-exitcode=234 ./build-examples/C++/FortranProblem/${{ matrix.config }}/fortran-problem-example
          valgrind --gen-suppressions=all --suppressions=scripts/valgrind/cpp.supp --error-exitcode=234 ./build-examples/C++/DLProblem/${{ matrix.config }}/dl-problem-example
          valgrind --gen-suppressions=all --suppressions=scripts/valgrind/cpp.supp --error-exitcode=234 ./build-examples/C++/DLProblem/${{ matrix.config }}/test-matmul
      - name: Run tests (Valgrind, ${{ matrix.config }})
        run: |
          valgrind --gen-suppressions=all --suppressions=scripts/valgrind/cpp.supp --error-exitcode=234 ./build-tests/${{ matrix.config }}/tests

  test-deb:
    needs: [build]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        host: [x86_64-bionic-linux-gnu]
        container:
          - 'debian:bullseye'
          - 'debian:bookworm'
          - 'debian:trixie'
          - 'debian:sid'
          - 'ubuntu:focal'
          - 'ubuntu:jammy'
          - 'ubuntu:noble'
          - 'ubuntu:rolling'
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: alpaqa-${{ matrix.host }}
          path: package
      - name: Update
        run: apt update
      - name: Install
        run: apt install -y ./package/*alpaqa*.deb
      - name: Run
        run: alpaqa-driver

  release:
    if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
    needs: [test, test-deb]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [x86_64-bionic-linux-gnu, aarch64-rpi3-linux-gnu]
    steps:
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: alpaqa-${{ matrix.host }}
        path: package
    - name: Release
      uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
      with:
        files: |
          package/alpaqa*.tar.gz
          package/*alpaqa*.deb
