name: Python Wheels

on:
  workflow_dispatch:
  release:
    types: ['released', 'prereleased']

env:
  PACKAGE_VERSION: '1.0.0a21.dev0'
  PACKAGE_NAME: alpaqa

jobs:
  # First we build the wheels natively (build system == host system).
  # This allows us to import the compiled modules, and automatically generate
  # stub files for them. Those stub files are then included in the sdist
  # (source distribution), to be later included in the cross-compiled packages
  # as well (because we can't generate stubs while cross-compiling).
  # By building the native wheels first, we can already start testing while the
  # cross-compiled versions are being built.
  build-sdist:
    name: Build sdist
    runs-on: ubuntu-22.04
    outputs:
      epoch: ${{ steps.get-epoch.outputs.epoch }}
    steps:
      - id: get-epoch
        run: |
          ts=$(date +%s)
          echo "epoch=$ts" >> $GITHUB_OUTPUT
          echo "SOURCE_DATE_EPOCH=$ts" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Conan
        uses: ./.github/workflows/setup-conan
        with:
          python-version: '3.12'
          cache-key: build-sdist

      - name: Build Wheel package
        run: ./scripts/ci/build-linux-native.sh . dist python
      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: native-wheels
          path: dist/*.whl
          retention-days: 1

      - name: Create sdist
        run: python3 -m build -s
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 1

      - run: conan cache clean

  # Testing is done in the official Python Docker container: https://hub.docker.com/_/python/
  # This should match more closely to the environment that users might use.
  # It also ensures that we don't accidentally depend on any libraries specific
  # to the build container.
  test-linux:
    name: Run tests
    needs: [build-sdist]
    runs-on: ubuntu-latest
    container: python:3.12-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: native-wheels
          path: dist

      - name: Install libgfortran
        run: apt-get update && apt-get install -y libgfortran5

      - name: Install
        run: python3 -m pip install --find-links=dist "${PACKAGE_NAME}[test]==${PACKAGE_VERSION}"

      - name: Test
        run: pytest -rP

  # After the native build, we have the stub files, and we can start cross-
  # compiling for all architectures.
  build-linux:
    name: Build (${{ matrix.host }})
    needs: [build-sdist]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [x86_64-bionic-linux-gnu, aarch64-rpi3-linux-gnu, armv7-neon-linux-gnueabihf, armv6-rpi-linux-gnueabihf]
    steps:
      - run: echo "SOURCE_DATE_EPOCH=${{ needs.build-sdist.outputs.epoch }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan and sccache
        uses: ./.github/workflows/setup-conan
        with:
          python-version: '3.12'
          cache-key: build-${{ matrix.host }}

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      - name: Extract sdist
        run: mkdir sdist && tar xf dist/*.tar.gz -C sdist --strip-components 1

      - name: Build Wheels
        run: |
          for v in 3.9 3.10 3.11 3.12 3.13 3.14; do
            ./scripts/ci/build-linux-cross.sh $v ${{ matrix.host }} sdist dist
          done

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.host }}
          path: ./dist/*.whl

      - run: conan cache clean

  test-linux-x:
    name: Import ${{ matrix.python-version }} ${{ matrix.host }}
    needs: [build-linux]
    runs-on: ${{ matrix.os }}
    container: '${{ matrix.python }}:${{ matrix.python-version }}${{ matrix.image-suffix }}-bookworm'
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04-arm']
        python: ['python']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        include:
          - os: 'ubuntu-latest'
            python: 'python'
            python-version: '3.14'
            image-suffix: '-rc'  # Set this to '-rc' to test pre-releases
            host: 'x86_64-bionic-linux-gnu'
          - os: 'ubuntu-24.04-arm'
            python: 'python'
            python-version: '3.14'
            image-suffix: '-rc'  # Set this to '-rc' to test pre-releases
            host: 'aarch64-rpi3-linux-gnu'
          - os: 'ubuntu-latest'
            host: 'x86_64-bionic-linux-gnu'
          - os: 'ubuntu-24.04-arm'
            host: 'aarch64-rpi3-linux-gnu'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-${{ matrix.host }}
          path: dist

      - name: Install
        run: python3 -m pip install --find-links=dist "${PACKAGE_NAME}==${PACKAGE_VERSION}"

      - name: Import
        run: objdump -p "$(python3 -c 'import alpaqa; print(alpaqa._alpaqa.__file__)')"

  # Build for Windows and macOS using cibuildwheel.
  # Since we're not specifying any cross-compilation settings, py-build-cmake
  # will use its default cross-compilation settings for Windows on ARM64.
  # For macOS, we build universal wheels that work on both Intel and ARM macs.
  build-macos-windows:
    name: Build (${{ matrix.cibw-arch }}-${{ matrix.os }})
    needs: [build-sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {os: windows-latest, cibw-arch: AMD64, arch: amd64}
          - {os: windows-latest, cibw-arch: x86, arch: amd64_x86}
          - {os: windows-latest, cibw-arch: ARM64, arch: amd64_arm64}
          - {os: macos-latest, cibw-arch: universal2}
          - {os: macos-latest, cibw-arch: x86_64}
          - {os: macos-latest, cibw-arch: arm64}
      fail-fast: false
    env:
      SCCACHE_CACHE_MULTIARCH: "1"
      CIBW_ARCHS: ${{ matrix.cibw-arch }}
      CIBW_ENABLE: 'pypy'
      CIBW_TEST_SKIP: 'pp* *-win32 cp314*'
    steps:
      - run: echo "SOURCE_DATE_EPOCH=${{ needs.build-sdist.outputs.epoch }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conan and sccache
        uses: ./.github/workflows/setup-conan
        with:
          python-version: "3.12"
          cache-key: cibuildwheel-${{ matrix.cibw-arch }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel~=3.1.3

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      - name: Extract sdist
        shell: bash
        run: mkdir sdist && tar xf dist/*.tar.gz -C sdist --strip-components 1 && cp -a scripts sdist

      - name: Build wheels
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
          cibuildwheel sdist --output-dir dist

      - name: Build wheels
        if: runner.os != 'Windows'
        run: cibuildwheel sdist --output-dir dist

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.cibw-arch }}
          path: ./dist/*.whl

      - run: conan cache clean

  # This step checks the package version before release (to make sure that the
  # package version actually matches the version of the GitHub release tag),
  # and uses Twine to check the metadata of the packages.
  check-release:
    name: Check release
    needs: [build-sdist, test-linux, build-linux, build-macos-windows]
    runs-on: ubuntu-latest
    container: python:3.12-bullseye
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Install package
        run: python -m pip install --no-deps --no-index --find-links=dist ${PACKAGE_NAME}==${PACKAGE_VERSION}
      - name: Check package version
        if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
        run: |
          version="$(python -c 'from importlib.metadata import version as v; print(v("${{ env.PACKAGE_NAME }}"))')"
          [ "${{ github.event.release.tag_name }}" = "$version" ]
        shell: bash
      - name: Twine check
        run: |
          python -m pip install twine
          twine check dist/*

  # Here we download the sdist and the built Wheel files, and upload them to
  # TestPyPI. You should follow the trusted publishing instructions in the
  # https://github.com/pypa/gh-action-pypi-publish README and on
  # https://docs.pypi.org/trusted-publishers carefully!
  release:
    name: Release
    needs: [check-release, test-linux-x]
    if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
    runs-on: ubuntu-latest
    environment:
      name: release
      # url: https://test.pypi.org/p/${{ env.PACKAGE_NAME }}
      url: https://pypi.org/p/${{ env.PACKAGE_NAME }}
    permissions:
      id-token: write  # mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        # with:
        #   repository-url: https://test.pypi.org/legacy/
