name: 'CI Tests: Python'

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  release:
    types: ['released', 'prereleased']

env:
  PACKAGE_VERSION: "1.0.0a21.dev0"
  PACKAGE_NAME: alpaqa

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [relwithdebinfo, debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Conan
        uses: ./.github/workflows/setup-conan
        with:
          python-version: '3.12'
          cache-key: build-sdist

      - name: Build Wheel package
        run: ./scripts/ci/build-linux-hardened.sh . dist ${{ matrix.config }}

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: hardened-wheels-${{ matrix.config }}
          path: dist/*.whl
          retention-days: 1

      - run: conan cache clean

  test-linux:
    needs: [build-linux]
    runs-on: ubuntu-latest
    container: python:3.12-trixie
    strategy:
      matrix:
        config: [relwithdebinfo, debug]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: hardened-wheels-${{ matrix.config }}
          path: dist

      - name: Install Valgrind, libgfortran
        run: apt-get update && apt-get install -y valgrind libgfortran5 --no-install-recommends

      - name: Install test dependencies
        run: python3 -m pip install -U pip cmake ninja twine
      - name: Install
        run: python3 -m pip install --find-links=dist "${PACKAGE_NAME}[test]==${PACKAGE_VERSION}"

      - name: Test (${{ matrix.config }})
        run: python3 -m pytest -rP
        env:
          ALPAQA_PYTHON_DEBUG: ${{ matrix.config == 'debug' }}

      - name: Test (Valgrind, ${{ matrix.config }})
        run: valgrind --gen-suppressions=all --suppressions=scripts/valgrind/python.supp --error-exitcode=234 python3 -m pytest -rP
        env:
          ALPAQA_PYTHON_DEBUG: ${{ matrix.config == 'debug' }}

      - name: Check Wheel metadata
        run: python -m twine check dist/*.whl

  build-macos:
    if: false
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: '11.0'
    steps:
      - uses: actions/checkout@v4

  build-windows:
    if: false
    runs-on: windows-2022
    strategy:
      matrix:
        arch: ['AMD64']
        python-id: ['cp310-*']
    env:
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v4

  docs:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      # Necessary tools
      - name: Install git and other tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends \
              git ca-certificates make \
              texlive-bibtex-extra graphviz \
              libcapture-tiny-perl libdatetime-perl libdevel-cover-perl \
              libdigest-md5-file-perl libjson-xs-perl perl
      # Git clone
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      # Conan
      - name: Set up Conan
        uses: ./.github/workflows/setup-conan
        with:
          python-version: '3.12'
          cache-key: docs
      # Doxygen
      - name: Install Doxygen
        run: >
          wget -O- https://github.com/doxygen/doxygen/releases/download/Release_1_14_0/doxygen-1.14.0.linux.bin.tar.gz | 
          sudo tar xz -C /usr/local/bin doxygen-1.14.0/bin/doxygen --strip-components=2
      # LCOV
      - name: Install LCOV
        run: |
          git clone --single-branch --depth=1 --branch "v2.3.2" \
              https://github.com/linux-test-project/lcov.git
          sudo make -C lcov install PREFIX="/usr/local"
        working-directory: /tmp
      # Create a copy of the repo in /tmp/staging.
      # Create the `gh-pages` branch if it doesn't exist already, check it out.
      - name: Create staging area
        run: |
          rm -rf /tmp/staging
          cp -ar $GITHUB_WORKSPACE/ /tmp/staging
          git config --global --add safe.directory /tmp/staging
          cd /tmp/staging
          git fetch origin gh-pages:gh-pages ||:
          git checkout gh-pages || \
          { git checkout --orphan gh-pages && git rm -rf . && git clean -fxd ; }
          echo -e 'bib*.aux\ncitelist.doc*\npy-build-cmake\n.conan2\nbuild\ntttapa-conan-recipes' > .gitignore
      # Download and install package, Install dependencies for generating docs
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: hardened-wheels-relwithdebinfo
          path: dist
      - name: Install dependencies
        run: |
          python3.12 -m pip install -U pip
          python3.12 -m pip install --find-links=dist "${PACKAGE_NAME}[docs]==${PACKAGE_VERSION}"
          python3.12 -m pip install -r doxygen/requirements.txt
      # Generate the documentation and save it in /tmp/staging
      - name: Generate documentation
        run: |
          ./doxygen/scripts/gen-docs.sh /tmp/staging
          ./doxygen/scripts/gen-docs-index.sh /tmp/staging md
      # Commit the new documentation, squash the commits, and push it to GitHub
      - name: Commit and push documention
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          commithash=$(git rev-parse HEAD)
          cd /tmp/staging
          git add .
          git commit -m "Documentation for ${commithash}" && \
          git reset $(git commit-tree HEAD^{tree} -m "Documentation for ${commithash}") && \
          git push -f origin gh-pages ||:
